### ISSUE TITLE
Support setTimeout/interval natively

### ISSUE THREAD

**Issue by sinni800** [robertkrimen/otto#105]
I know there's natto, but I think it would be great to have an (optional?) permanent Loop for events like this. Maybe this loop would then actually do everything in JS and not the goroutine calling the JS code. This would make the single-threadedness easier to implement in a multithreaded go scenario at the same time.

**Comment by deoxxa** [comment]
I put together [ottoext](https://godoc.org/fknsrs.biz/p/ottoext) a little while ago - it does much the same thing as natto, but in a more flexible way (the loop is a standalone component, for example). I wonder if it'd be worth making it part of otto, perhaps as a sub-package? @stevenh what do you think?

**Comment by deoxxa** [comment]
I'm going to close this for now, as it's a year old - please feel free to open another issue if you're still interested in this, @sinni800.
