### ISSUE TITLE
What JavaScript/ECMAScript version does Otto comply to?

### ISSUE THREAD

**Issue by onlyafly** [robertkrimen/otto#109]
The documentation does not specify which version it complies to or attempts to comply to. Due to the regular expression incompatibility it would not strictly comply to any spec, but leaving that out, which is it closest to?

Is there any test suite which Otto has been run against (or could be run against) to see what the incompatibilities are?

**Comment by robertkrimen** [comment]
ECMAScript 5.1

http://www.ecma-international.org/ecma-262/5.1/

It was written against the above specification.

Besides the internal test suite, I run it against test262: http://test262.ecmascript.org/

I'll add this to the documentation, thanks.
