### ISSUE TITLE
upgrade underscore

### ISSUE THREAD

**Issue by emicklei** [robertkrimen/otto#110]
Hi,

I noticed that the underscore package is build from 1.4.4. A lot has changed [1] since that release. The official Javascript lib is now at 1.8.2.  

I am about to use this package in my project and would like to know if others already have attempted to upgrade to a newer version. If not, I like to contribute by doing just that.

[1] http://underscorejs.org/#changelog

**Comment by stevenh** [comment]
Could you put in a Pull Request for this @emicklei ?

**Comment by emicklei** [comment]
yes, I will prepare the PR for this.
