### ISSUE TITLE
Parse not working for anonymous function

### ISSUE THREAD

**Issue by JoeBruner** [robertkrimen/otto#120]
If I try to parse an anonymous function it doesn't appear to work.

Example:

    fnGood := "function x(){emit(this.DocName, 1)}"
    fnBad :=  "function  (){emit(this.DocName, 1)}"

    parser.ParseFile(nil, "", fnGood, 0) // OK
    parser.ParseFile(nil, "", fnBad,0) // (anonymous): Line 1:10 Unexpected token ( (and 11 more errors)

**Comment by fluxxu** [comment]
try
```go
fnBad :=  "(function  (){emit(this.DocName, 1)})"
```

**Comment by robertkrimen** [comment]
`fnBad` is actually invalid JavaScript, try it here as well: http://esprima.org/demo/parse.html

thanks @fluxxu

**Comment by JoeBruner** [comment]
Invalid in what sense?  If you wrap it in ()'s like @fluxxu says, it works.  If you assign it to a variable it works.  If you pass it as your map or reduce function to MongoDb, which uses the V8 engine it works.  Seems perfectly valid to me.

**Comment by JoeBruner** [comment]
Hrrm. This has a pretty good explanation, but doesn't explain why I'm able to pass fnBad to MongoDb and it still works.  https://jslinterrors.com/missing-name-in-function-statement

**Comment by robertkrimen** [comment]
Invalid according to the ECMA specification: http://www.ecma-international.org/publications/standards/Ecma-262.htm

node will not parse `fnBad` either

**Comment by robertkrimen** [comment]
MongoDb may be expecting an expression and not a statement, so they're pre-wrapping everything in parentheses.
