### ISSUE TITLE
Can you make it possible to inject deterministic support?

### ISSUE THREAD

**Issue by shutej** [robertkrimen/otto#125]
For instance, I'd like stuff like the random, date, and time builtins to come from an interface value injected into the VM.  The VM can use a default (package internal) interface in the constructor.

As part of this effort, it'd be helpful to use a [func (*Rand) Float64](https://golang.org/pkg/math/rand/#Rand.Float64) instead of the package default.

This seam would make it easier to write Go examples and tests, it would make it easier to get repeatable behavior in a server context.

**Comment by stevenh** [comment]
Sounds interesting, feel fee to put in a Pull Request for this.

**Comment by fjl** [comment]
math.random can be overridden as of https://github.com/robertkrimen/otto/pull/163
