### ISSUE TITLE
TypeError: Cannot access member 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by AnotherGoogleFans** [robertkrimen/otto#137]
source code is :
if (navigator.appVersion.toLowerCase().indexOf("android")>-1)
{
		var url="https://admin.appnext.com/offerWallApi.aspx?cnt=1&r=y&id="+getQueryByName("ida")+"&pbk="+getQueryByName("pbk")+"&rnd="+(Math.random()*100)+"&subid="+getQueryByName("subid");
		 window.location.href = url;
}

and I tried:

type Navigator struct {
	AppVersion string
}

myotto := otto.New()
mynavigator := Navigator{
	AppVersion: "Android 5.1.1",
}
myotto.Set("navigator", mynavigator)
myotto.Run(......)

then  return  error like this issue's title

**Comment by dyatlov** [comment]
@AnotherGoogleFans try to set `appVersion` instead of `AppVersion`

**Comment by stevenh** [comment]
Invalid code due to incorrect case, closing
