### ISSUE TITLE
[RFC] Runtime inspection/reflection

### ISSUE THREAD

**Issue by darkliquid** [robertkrimen/otto#145]
Building on #142, having some kind of data available from the runtime that allows you to inspect the current execution context and get useful information would be helpful for debugging and potentially other uses.

Just bouncing some ideas around, but as a rough idea, what I'd like to see is something that returns the following info, callable from the runtime at any time:

 * current line number/file
 * list of variables/functions currently available (maybe a map of symbols to otto.Value's?)
 * stacktrace

Maybe this might work as simply as a calling something like `*otto.Context()` and getting back a struct with some info.

Any thoughts? Does this sound useful? Is it even plausible?

**Comment by deoxxa** [comment]
This would be very useful indeed.

Getting the current line number shouldn't be too hard. We'd have to attach some more information during the parse process (e.g. [DebuggerStatement](https://github.com/robertkrimen/otto/blob/e6768252c24950d0eb61db1d6369e56befc92b20/cmpl_parse.go#L221-L222)) and keep track of the node we're evaluating. I think. I'm not too familiar with how those bits fit together, so I might be wrong.

Getting the current stack trace is totally doable - we've got that via `FunctionCall.CallerLocation`; it reads `scope` and `scope.parent` recursively until it hits nil.

Getting the current variables/functions should be pretty straightforward. We'd have to trace upwards through the scope and its parents (like a stack trace), collecting all the stash contents.
