### ISSUE TITLE
Storing comments

### ISSUE THREAD

**Issue by wolfgarnet** [robertkrimen/otto#148]
Hi!

I am working on a project where I am going to use comments to control some modification to javascript sources. I have therefore been working on a prototype, that stores comments in a separate map, that can be accessed after parsing. 
Would this be a feature, that could be accepted in the project?

**Comment by darkliquid** [comment]
Having that information makes it possible to use the parser in a preprocessing step to alter or generate code, much like the go:generate stuff in golang. If you wanted to use otto for that kind of tool, I could see this being useful.

Arguably though, it might just be easier in that scenario to just load the file and do some regex replacements/templating - it really depends on whether you need the context of the full AST of the javascript code or something along those lines.

In any event, no harm in submitting a PR for further discussion.

**Comment by wolfgarnet** [comment]
Cool!

I will need the full ast in context, because I need to modify it given adjacent comments.

**Comment by deoxxa** [comment]
I'd be interested to see how this works. One thing to keep in mind would be retaining line/column information. Depending on how drastic the changes to the source were, and at what point you made them (source text, AST, or program level), that might be tricky to do!

Keeping comment nodes in the AST would probably be neat though, and rather non-invasive.

**Comment by wolfgarnet** [comment]
I have made a pull request: #149
