### ISSUE TITLE
Is there a way to capture console output?

### ISSUE THREAD

**Issue by captncraig** [robertkrimen/otto#150]
I have a script that makes heavy use of `console.log`. This prints to Stdout fine, but I would like to inspect the output from my go code. Is there any way to provide a `Writer` to the vm to be used as the console output?

**Comment by deoxxa** [comment]
What you can do is set your own `console` object, kind of like this:

```go
vm.Set("console", map[string]interface{}{
  "log": func(c otto.FunctionCall) otto.Value {
    doSomethingWith(c.Args(0).String())

    return otto.UndefinedValue()
  },
})
```

I haven't actually run that code, so it might not work exactly as-is, but that's about the gist of things!
