### ISSUE TITLE
Question: Project & Functionality Status

### ISSUE THREAD

**Issue by dc0d** [robertkrimen/otto#153]
Having a pure Go interpreter for a dynamic language is fantastic! I wanted to use TypeScript (which gets compiled to JavaScript) with Go. I wondered what is the status of this project? Is it still active & maintained? Does it cover ES5? ES6 (since TypeScript gets compiled to ES5 & ES6)?

**Comment by deoxxa** [comment]
This project is indeed still active and maintained, and targets ES5. You should be able to run the compiled output of TypeScript - I personally am running ES6/ES7 code via babel on otto. If you run into anything that doesn't work, please raise an issue.
