### ISSUE TITLE
UTF-8 validation is too strict

### ISSUE THREAD

**Issue by Danprot** [robertkrimen/otto#159]
UTF-8 validation is too strict.
V8 and windows JS engines run scripts with strings with invalid characters just fine.

The attached script produces error
Eval error "(anonymous): Line 1:112 Invalid UTF-8 character..."
[chars_sample.js.txt](https://github.com/robertkrimen/otto/files/127782/chars_sample.js.txt)

Removing this validation in parser\lexer.go doesn't seem to affect anything.

**Comment by stevenh** [comment]
This seems to work with the following test:
```go
func Test_issue159(t *testing.T) {
	vm := New()
	val, err := vm.Run(`
		var Chars =" !\"#$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_` + "`" + `abcdefghijklmnopqrstuvwxyz{|}~€???????????Ž????????????ž? ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþ ";
		function CharToAscii(c){
			return Chars.indexOf(c) + 32;
		}
		CharToAscii('A');
	`)
	require.NoError(t, err)
	exp, err := val.Export()
	require.NoError(t, err)
	require.Equal(t, float64(65), exp)
}
```
