### ISSUE TITLE
Different error type for re2 errors

### ISSUE THREAD

**Issue by terinjokes** [robertkrimen/otto#160]
I'm currently using otto to parse JavaScript into an AST, and thus not using any of the runtime functionality.

Is it possible for the errors from re2 to be of a different type so I can distinguish (and ignore) them in the ErrorList?

**Comment by deoxxa** [comment]
Do you know about the `IgnoreRegExpErrors` mode for the parser?

**Comment by deoxxa** [comment]
I know it's not a direct answer to your question, but I figure it might actually do what you want in an easier way :)

**Comment by terinjokes** [comment]
Ah, no, I did not. I think that will get me going again, until the next error I want to ignore.

**Comment by deoxxa** [comment]
Are there other things you might want to ignore? Are the (partial) results from the parser even useful for you if it returns an error?

**Comment by terinjokes** [comment]
@deoxxa I do not yet know all my unknowns. It may be possible in the future I want to ignore other errors. It may be possible I want to group errors and provide nice reporting on them.

With a single error type with no disambiguation, either becomes much more difficult.

**Comment by deoxxa** [comment]
Right, being able to tell what kind of error the parser encountered would probably be nice. This is all interesting to me, as I know there are a couple of other people using the parser without specifically using the interpreter. Do keep me posted on what you end up with!
