### ISSUE TITLE
keypress input?

### ISSUE THREAD

**Issue by altsheets** [robertkrimen/otto#162]
How can I react to keypress? 

    function statusLoop(){
    	while (true){ 
    		statusPrint()
    		sleep(3000)
    		// stop at keypress? how to do that in otto?
    		// until then: Kill the process to end the loop.
    	}
    }

Thanks.

**Comment by deoxxa** [comment]
That's actually not part of JavaScript, I'm afraid! It's part of the DOM API that browsers implement.

Now, in saying that, I can see two ways you might do what you want.

1) You can set up a couple of goroutines, run the JavaScript in one, listen for keypresses in another, and use the `Interrupt` channel of your running otto VM to forcibly terminate whatever's executing. See [this part of the readme](https://github.com/robertkrimen/otto#halting-problem) for a bit of an idea on how to do that.

2) You could use a fully-fledged event loop (like [natto](https://github.com/robertkrimen/natto) or my own [ottoext](https://github.com/deoxxa/ottoext)) and implement _just enough_ of the browser APIs to do what you want.

Both of these approaches will involve a decent chunk of work for you.

**Comment by altsheets** [comment]
Thanks a lot. I might look into that. Had hoped it is easy. If not, I will just kill the process.

I am using the ethereum implementation of otto.

**Comment by deoxxa** [comment]
You'd have to take this up with the ethereum people then, I'd say. If they want to do something like this, and need some help getting started, do feel free to point them here!
