### ISSUE TITLE
Can I use javascript Math functions?

### ISSUE THREAD

**Issue by hiobairo** [robertkrimen/otto#175]
Hello...
I was trying to use JavaScript Math functions, and when I use `vm.run()`, return the follow error:
```js
"TypeError: 'trunc' is not a function at <anonymous>"
```
So I am asking... can I use some Math functions with otto? thanks

**Comment by deoxxa** [comment]
Otto implements all of the ES5 `Math` functions. According to [the MDN page for Math.trunc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc), that particular function is not actually part of a standard yet. However, that page also has a polyfill, and it should work fine on otto.
