### ISSUE TITLE
Array.reduce has String type for index.

### ISSUE THREAD

**Issue by martinhbramwell** [robertkrimen/otto#177]
I get very different behaviour running a simple line of Javascript in jsFddle vs Javascript in Otto . . . 

```
var ii = 33;
[3, 2, 1].reduce(function(pv, cv, ci, q) { var v = ci + ii; console.log(" v : " + v); return cv; });
```

In jsFiddle the result is . . .

```
v : 34
v : 35
```

. . . whereas in Otto in the Ethereum Geth REPL . . .

```
v : 133
v : 233
```

Otto unit tests assume only two arguments to the reduce callback function : [func TestArray_reduceRight(t *testing.T)}](https://github.com/robertkrimen/otto/blob/master/array_test.go#L635), but it should test the handling of **four** :  [MDN >> Array.prototype.reduce()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce)

**Comment by deoxxa** [comment]
Right, yep - seems clear enough: [ECMAScript 5.1 sec-15.4.4.21](http://www.ecma-international.org/ecma-262/5.1/#sec-15.4.4.21) describes `callbackfn` as being _"called with four arguments: the previousValue (or value from the previous call to callbackfn), the currentValue (value of the current element), the currentIndex, and the object being traversed"_.

Should be easy enough to fix.

**Comment by deoxxa** [comment]
Interestingly, ECMA-262 doesn't seem to specify the type of the `currentIndex` value. Presumably other engines are making it a number. We might want to confirm that behaviour by reviewing other engines' behaviours.
