### ISSUE TITLE
thrown errors missing info

### ISSUE THREAD

**Issue by cvillecsteele** [robertkrimen/otto#179]
Works elsewhere, not in otto:

```
    function getErrorObject(){
        try { throw Error('') } catch(err) { return err; }
    }

    var err = getErrorObject();
    console.log(JSON.stringify(err, null, 2));
    var caller_line = err.stack.split("\n")[4];
    var index = caller_line.indexOf("at ");
    var clean = caller_line.slice(index+2, caller_line.length);
```

**Comment by deoxxa** [comment]
While I agree that this is a useful feature (`Error.stack`), it's also not actually specified in ECMA-262. See [section 15.11](http://www.ecma-international.org/ecma-262/5.1/#sec-15.11).

It's still worth adding though I think, so I'll keep this open.

**Comment by deoxxa** [comment]
@cvillecsteele take a look at https://github.com/robertkrimen/otto/pull/180 and see if it does what you want. Be aware that there's _no specification_ for the value of `stack`, and it _will_ change in the future to support native functions in stack traces.

**Comment by cvillecsteele** [comment]
@deoxxa Looks good.  Thanks.
