### ISSUE TITLE
Otto calling gopherjs ?

### ISSUE THREAD

**Issue by joeblew99** [robertkrimen/otto#182]
It's temping right ???

**Comment by joeblew99** [comment]
I was joking around a bit, but someone has done it.

https://github.com/hajimehoshi/otto-gopherjs

Ah it sooo inception :)

**Comment by deoxxa** [comment]
I mean... There's not really anything that would make it not work... But it does seem a bit pointless!

I hope you don't mind if I close this issue, since there's no action to take :)

**Comment by joeblew99** [comment]
No probs..
