### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by prsolucoes** [robertkrimen/otto#183]
Hi,

I dont find any contact here, so i decide write here.

How long this project is supported? 
It has an active development?
Everything is working fine with Go 1.6?

I want put it on my open-source project like Jenkins, but made with Go. I need a script language user make their script to deploy.

**Comment by deoxxa** [comment]
This project is active, yep! Just check out the git activity if you'd like to see. Everything works okay with Go 1.6.
