### ISSUE TITLE
concurrent otto?

### ISSUE THREAD

**Issue by donpdonp** [robertkrimen/otto#184]
Firstly thanks for this project, its amazing. I'm using otto to evaluate user-provided js. A go method is exposed to the js environment to allow the user js scripts to make http page loads. Since this is asynchronous, the https reponse comes into a go routine to listen for responses. A otto callback into the js is executed, and since this is not the main go routine, there is the potential for concurrent access and after a couple days of running that happens. At least thats my take from it based on the error logs.

Is this simply not advisable with otto?

it looks like the list/map of properties ```self.property[name]``` (from the error on  slash.go:159)  is whats being concurrently accessed.

```
fatal error: concurrent map read and map write
```
full error at https://gist.github.com/donpdonp/e22583dce93a709b20ed657e27663582

**Comment by deoxxa** [comment]
Yep, that'll break. I've written a library to do this properly though - [fknsrs.biz/p/ottoext](https://godoc.org/fknsrs.biz/p/ottoext). Take a look at [the fetch tests](https://github.com/deoxxa/ottoext/blob/master/fetch/fetch_test.go) to see how you might use it.

**Comment by donpdonp** [comment]
awesome. I'll take a look at try to do things that way.

**Comment by deoxxa** [comment]
Let me know how you go! The documentation for that library is a bit sparse, so feel free to ask me if you have any problems.
