### ISSUE TITLE
Calling a Go function with the wrong arguments takes down the host program

### ISSUE THREAD

**Issue by deoxxa** [robertkrimen/otto#186]
(From https://github.com/robertkrimen/otto/issues/185#issuecomment-216706838)

I dont know if is a problem on otto or mine. Can you check?

Im exporting golang packages to otto:

> vm.Set("http", map[string]interface{}{
>       "Get": http.Get,
>       "Post": http.Post,
>       "PostForm": http.PostForm,
>       "NewRequest": http.NewRequest,
>   })

Im trying call from JS with few method arguments to check error handling:

> console.log(http.Post("https://httpbin.org/post"));

This method require 3 args and i set only one in js file. A panic error happen and process is stopped :(

> panic: reflect: Call with too few input arguments [recovered]
>   panic: reflect: Call with too few input arguments
> 
> goroutine 13 [running]:
> panic(0x5fbdc0, 0xc8203482d0)
>   /usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6

Could you help me?

**Comment by prsolucoes** [comment]
Hi,

Only to add info about this problem.

1 - Pass too many params
2 - Pass fewer params
3 - Pass param with different expected type

Thanks.

**Comment by prsolucoes** [comment]
I have created three tests. Can you put on final of file "function_test.go" to check:

```
func Test_lessParameters(t *testing.T) {
	tt(t, func() {
		test, vm := test()

		{
			vm.Set("abc", func(a string, b string, c string) int {
				return 1
			})

			test(`
                abc("a", "b")
            `, 1)
		}
	})
}

func Test_tooManyParameters(t *testing.T) {
	tt(t, func() {
		test, vm := test()

		{
			vm.Set("abc", func(a string, b string, c string) int {
				return 1
			})

			test(`
                abc("a", "b", "c", "d")
            `, 1)
		}
	})
}

func Test_invalidTypeParameter(t *testing.T) {
	tt(t, func() {
		test, vm := test()

		{
			vm.Set("abc", func(a string, b string, c string) int {
				return 1
			})

			test(`
                abc(1, 2, 3)
            `, 1)
		}
	})
}
```

**Comment by dhiltonp** [comment]
This error seems to be a fault in Terst, not otto itself.

```
package params_test
import (
	"errors"
	"testing"
	"github.com/robertkrimen/otto"
)

func ErrorTest(t *testing.T, script string, ex error) {
	vm := otto.New()
	vm.Set("abc", func(a string, b string, c string) int {
		return 1
	})
	vm.Set("num", func(a int, b int, c int) int {
		return 1
	})
	_, e := vm.Run(script)
	if e == nil && ex == nil {
		// no problem
	} else if e == nil {
		t.Errorf("received nil, not %s", ex.Error())
	} else if ex == nil {
		t.Errorf("received %s, not nil", e.Error())
	} else if e.Error() != ex.Error() {
		t.Errorf("received %s, not %s", e.Error(), ex.Error())
	}
}

func Test_lessParameters(t *testing.T) {
	ErrorTest(t,`abc("a","b")`, errors.New("RangeError: expected 3 argument(s); got 2"))
}

func Test_tooManyParameters(t *testing.T) {
	ErrorTest(t,`abc("a","b","c","d")`, errors.New("RangeError: expected 3 argument(s); got 4"))
}

func Test_validTypeParameterConversion(t *testing.T) {
	ErrorTest(t,`abc(1,2,3)`, nil)
}

func Test_validTypeParameter(t *testing.T) {
	ErrorTest(t,`num(1,2,3)`, nil)
}

func Test_invalidTypeParameterConversion(t *testing.T) {
	ErrorTest(t,`num("a","b","c")`, errors.New(`TypeError: can't convert from "string" to "int"`))
}```

```PASS
ok  	params	0.010s```

**Comment by dhiltonp** [comment]
I've added the exact http example, and I cannot replicate it.

@prsolucoes, can you provide full source that triggers this issue?

**Comment by stevenh** [comment]
Same here can't reproduce see PR which adds test.

If you can reproduce feel free to reopen.
