### ISSUE TITLE
Semantic versioning and Changelog

### ISSUE THREAD

**Issue by f4tq** [robertkrimen/otto#201]
Hi,

I want to vendor your project in another project but that project requires [Semantic Versioning](http://semver.org) accompanied by Changelog.md tied to those versions.

It seems like a minor-ish thing.  
Does it seem like something this project could do in the future? 
Thanks
Chris

**Comment by deoxxa** [comment]
I don't think that'll end up happening here - everyone's time is stretched thinly enough as it is. Unless you're volunteering your time to maintain it, that is!

**Comment by stevenh** [comment]
I will be using semantic versioned releases moving forward. Change logs will be built into each release.
