### ISSUE TITLE
nil dereference crash in MakeCustomError()

### ISSUE THREAD

**Issue by uppfinnarn** [robertkrimen/otto#202]
Easily replicated like so:

```go
otto.New().MakeCustomError("Error", "something went wrong")
```

This causes a crash [here](https://github.com/robertkrimen/otto/blob/ccf93984d916c04ccea151e4605ddc14430b01b4/error.go#L154), because there is no scope.

**Comment by deoxxa** [comment]
Good catch! Looks like `if rt != nil` needs to be `if rt != nil && rt.scope != nil`. Any chance you could make that change and put in a PR with a couple of tests? I should be able to get to it later this week if not.

**Comment by uppfinnarn** [comment]
There! #203

**Comment by deoxxa** [comment]
Merged! Thanks again :)
