### ISSUE TITLE
Request for documentation on printing/manipulating ast.Program

### ISSUE THREAD

**Issue by shanemhansen** [robertkrimen/otto#206]
I'm looking for information on how you might implement something like this: https://github.com/tdewolff/minify/tree/master/js using the otto parser.

Even a simple example for stripping comments and printing the AST would be helpful.

**Comment by nathan-osman** [comment]
I was wondering the same thing, but I was able to put a few pieces together by reading the source code. Here's a very basic example:

    // Create the AST
    program, _ := parser.ParseFile(nil, "something.js", "/* JS content */", 0)
    
    // Loop over all statements in the file, printing their type
    for _, stm := range program.Body {
        fmt.Printf("Statement: %T\n", stm)
    }

    // Given a particular statement, check to see if it is a function call
    if exp, ok := stm.(*ast.ExpressionStatement); ok {
        if call, ok := exp.Expression.(*ast.CallExpression); ok {
            // do something with call
        }
    }

    // Given a function call, print its properties
    if callee, ok := call.Callee.(*ast.Identifier); ok {
        ftm.Printf("Function call: %s\n", callee.Name)
    }
    fmt.Printf("Arguments: %d\n", len(call.ArgumentList))
