### ISSUE TITLE
Relative imports

### ISSUE THREAD

**Issue by titpetric** [robertkrimen/otto#207]
Otto uses relative imports, which are also not supported when using go vendoring.

Specifically, even gvt doesn't support them:

```
# gvt fetch  "github.com/robertkrimen/otto"
2016/07/21 13:07:04 Fetching: github.com/robertkrimen/otto
2016/07/21 13:07:09 · Fetching recursive dependency: ./terst
2016/07/21 13:07:09 command "fetch" failed: error fetching ./terst: "./terst" is not a valid import path
```

Could you change the imports to a FQDN as opposed to the relative `./` which is used now?

**Comment by vdobler** [comment]
This issue bugged me too: It makes vendoring otto a pain.

**Comment by tyler-sommer** [comment]
Note this also prevents github.com/golang/dep (and github.com/sdboyer/gps) from working with otto.

@stevenh Would there be any issue with changing the import to the fully qualified name? I can make the changes and submit a PR if it has a good chance of being accepted. Thanks!

**Comment by stevenh** [comment]
Nope these should be changed to full qualified, happy to accept a PR
