### ISSUE TITLE
is it possible to write to filesystem with npm "fs" or other way

### ISSUE THREAD

**Issue by lyricalpolymath** [robertkrimen/otto#208]
I'm trying to understand if from within the geth console (Ethereum) 
which, as[ it says, is an Otto JS VM](https://github.com/ethereum/go-ethereum/wiki/JavaScript-Console#caveat), I can save the output to a text file.

I've tried requiring fs but it doesn't find it.

Is there a way to write to disk from Otto? or call a Go function that does that (if it's not declared)? 

thanks

**Comment by deoxxa** [comment]
Short answer "no." Long answer "yes, if you implement it." Otto is just a JavaScript interpreter, and doesn't supply any non-standard functions (e.g. filesystem or network access).

**Comment by lyricalpolymath** [comment]
ok thanks, but how would one go about to that.. if it's an interpreter it is sandboxed, isn't it? 
by implementing you mean exposing a Go function that can be called from Otto that could do the trick?

**Comment by darkliquid** [comment]
I've written some basic filesystem access stuff I've exposed to an otto VM before for things, but I'd recommend looking at writing a wrapper around something like https://github.com/spf13/afero that exports the methods into the VM if you want something more reusable and modular, longterm.
