### ISSUE TITLE
Redirect output to a log.Logger (...)

### ISSUE THREAD

**Issue by titpetric** [robertkrimen/otto#209]
When using console.log for example, the output gets printed to os.Stdout. It would be great if Otto has a logger property (otto.log) which would implement log.Logger, and we could change it to catch/redirect output.

**Comment by deoxxa** [comment]
Take a look at https://github.com/robertkrimen/otto/issues/150#issuecomment-165582875 - it should get you where you want to be.

**Comment by titpetric** [comment]
Ah, thanks. I did realize over vm.Set that setting a console struct will not work because 'log' is private, and I'd have to use 'Log' or something. Of couse I'm half way modifying Otto so it will take an io.Writer interface to replace os.Stdout....
