### ISSUE TITLE
Handle conversion of struct, map and slice from go to js

### ISSUE THREAD

**Issue by muka** [robertkrimen/otto#212]
Currently `toValue_reflectValuePanic` panic on go struct, map and slice, in practice supporting only primitive in conversion.

It may render struct with encoding/json, create plain js objects out of map and array of slices and viceversa.

What are the drawbacks you see in a similar implementation?

Thank you

**Comment by tyler-sommer** [comment]
Otto supports transforming these types, but with one caveat: it requires an otto runtime.

As an example:

```go
package main

import (
    "fmt"
    "github.com/robertkrimen/otto"
)

func main() {
    vm := otto.New()
    v, err := vm.ToValue(map[string]interface{}{
        "test": 1,
    })
    if err != nil {
        fmt.Println(err)
    } else {
        fmt.Println("converted value: ", v)
    }
}
// Output:
// converted value:  [object Object]
```


Cheers.

**Comment by muka** [comment]
Ok, closing as it is not a issue. Thank you!
