### ISSUE TITLE
Error setting a go object from runtime

### ISSUE THREAD

**Issue by pytlesk4** [robertkrimen/otto#214]
``` go
package main

import (
    "encoding/json"
    "fmt"

    "github.com/robertkrimen/otto"
)

var runtime = otto.New()
var objJSON = `{
  "bear": [
    "foo",
    "fooo"
  ]
}`

func getObj(call otto.FunctionCall) otto.Value {
    var obj interface{}
    json.Unmarshal([]byte(objJSON), &obj)
    ottoResult, _ := runtime.ToValue(obj)

    return ottoResult
}

func setObj(call otto.FunctionCall) otto.Value {
    obj, _ := call.Argument(0).Export()
    objBytes, _ := json.MarshalIndent(obj, "", "  ")
    // Expected output:
    /*
       {
         bear: {
           "foo": "bug"
         }
       }
    */
    fmt.Println(string(objBytes))
    // Actual output:
    /*
       {
         bear: {}
       }
    */
    return otto.UndefinedValue()
}

func main() {
    runtime.Set("getObj", getObj)
    runtime.Set("setObj", setObj)
    runtime.Run(`
            var obj = getObj();
            obj.bear = {
                "foo": "bug"
            };
            setObj(obj);
    `)
}
```

Modifying a object that is passed into the vm doesn't behave as expected.  Is there something I am doing wrong?

**Comment by llonchj** [comment]
+1

**Comment by pytlesk4** [comment]
@llonchj nope, I was hoping this was going to be fixed by now, and I don't have the time to fix it because I don't have any idea how otto works internally. I have a temporary solution right now and stringify then parse any object I put into the vm.

``` go
func main() {
    runtime.Set("getObj", getObj)
    runtime.Set("setObj", setObj)
    runtime.Run(`
            var obj = JSON.parse(JSON.stringify(getObj()));
            obj.bear = {
                "foo": "bug"
            };
            setObj(obj);
    `)
}
```

This will do what I expect, but it comes at the extra cost of a deep copy.

**Comment by llonchj** [comment]
https://github.com/samuelhug/otto

**Comment by pytlesk4** [comment]
Thank you so much! Can you make a pull request too, it would be great if they merge your fixes in!

**Comment by llonchj** [comment]
Sorry, it is not my own repo.
If you open a issue there asking for PR i will +1 once you let me know

2016-12-06 11:04 GMT+11:00 Thomas Pytleski <notifications@github.com>:

**Comment by dhiltonp** [comment]
Otto has internal Values that implement the basic JS types, like an array: https://github.com/robertkrimen/otto/blob/master/type_array.go

Otto also has the ability to work on Go objects natively, like a slice:
https://github.com/robertkrimen/otto/blob/master/type_go_array.go

The full set of javascript operations are defined for JS types, but not for go types. I think this could be worked around, but it's not straightforward due to the difference in type systems of Go and JS. In particular, a JS array can have a mix of arbitrary types but Go can't (for every array type). An array in Go cannot be cast from []string to []interface, it requires a deep copy.

**Comment by chesson1017** [comment]
hey, you should use pointer object like this

func getObj(call otto.FunctionCall) otto.Value {
    var obj interface{}
    json.Unmarshal([]byte(objJSON), &obj)
    ottoResult, _ := runtime.ToValue(&obj)

    return ottoResult
}

**Comment by stevenh** [comment]
This works as expected:
```go
func Test_issue214(t *testing.T) {
	vm := New()
	var objJSON = `{
	  "bear": [
		"foo",
		"fooo"
	  ]
	}`

	getObj := func(call FunctionCall) Value {
		var obj interface{}
		json.Unmarshal([]byte(objJSON), &obj)
		ottoResult, _ := vm.ToValue(obj)

		return ottoResult
	}

	setObj := func(call FunctionCall) Value {
		obj, err := call.Argument(0).Export()
		require.NoError(t, err)

		buf, err := json.Marshal(obj)
		require.NoError(t, err)
		require.Equal(t, `{"bear":{"foo":"bug"}}`, string(buf))
		return UndefinedValue()
	}

	err := vm.Set("getObj", getObj)
	require.NoError(t, err)
	err = vm.Set("setObj", setObj)
	require.NoError(t, err)
	_, err = vm.Run(`
            var obj = getObj();
            obj.bear = {
                "foo": "bug"
            };
            setObj(obj);
    `)
	require.NoError(t, err)
}
```
