### ISSUE TITLE
Setting a JavaScript function in a otto Object

### ISSUE THREAD

**Issue by Slals** [robertkrimen/otto#221]
Hi,

I'm writing a lib that allows to parse a js object, then setting attributes and functions and rebuild it in js. Otto helps a lot to do this.

When I use for instance 

``` go
vm := otto.New()
obj, _ := vm.Object("obj = {fn: function(){ //js stuff }}")
fn, _ := obj.Get("fn")
fn.IsFunction() // True
```

Everything is ok, the `Value` returned is a function, but setting a function to an `Object` appears to be impossible unless I miss something, here is an example

``` go
obj.Set("newFn", "function(){ //js stuff }")
fn, _ := obj.Get("newFn")
fn.IsFunction() // False
fn.IsString() // True
```

The function is set as it is a `string` which is normal since the function `Get` expects an `interface{}` and I put a string ( which I hope it could recognise this as a javascript function).

I did this ugly workaround for now

``` go
// obj is the js obj where I want to set a new function
tmpObj, _ := vm.Object("({tmp: function(){ //js stuff }})")
fn, _ := tmpObj.Get("tmp")
obj.Set("newFn", fn)
```

I'm not sure if Otto should allow to build some kind of anonymous functions. I tried to use `FunctionCall` struct but I feel like it's only made to compile go function in javascript.

I tried to mimic `Object` [here](https://github.com/robertkrimen/otto/blob/3e7ca9f1929a7f90c674390834e6495bcd09836a/otto.go#L618) for functions but I had issues.

**Comment by prijip** [comment]
I wanted to do a similar thing, and came across this post when searching for documentation on Otto.  Later I implemented it using `vm.Call("Function"...)`.  Just sharing my notes on how I did it.

To create a function "sum(a, b)":
```golang
    functionBody := ` {
        return a + b;
    }
    `
    vm := otto.New()
    fn, err := vm.Call("Function", nil, "a", "b", functionBody)
```

The created function object can be invoked using the returned `Value` fn:

```golang
    a := 4
    b := 8
        
    sum, err := fn.Call(otto.NullValue(), a, b)
```

To set it as a function named "sum":
```golang
    vm.Set("sum", fn)
    sum, err := vm.Call("sum", nil, a, b)
```
