### ISSUE TITLE
How down VM ?

### ISSUE THREAD

**Issue by guiferpa** [robertkrimen/otto#224]
I've a VM inside of a goroutine, but I don't know shutdown my VM process. How do it ?

I exit from my goroutine my the process continue executing, I want donw my VM, case I've an code in JavaScript like:

``` js
while (true) {
   console.log("Loop here !!!");
}
```

I don't know down it with timeout error/status

**Comment by gpaixao** [comment]
I see now `vm.Interrupt chan func()` but when use it my VM not down, I need use `panic()`, but using `panic` I down my app, but I wan't it. How do it ?

**Comment by dhiltonp** [comment]
vm.Interrupt is the way to do it. You have to initialize the chan yourself, then send an appropriate func.

If you provide a full example, it could be troubleshot. As is, all I can say is "try again."
