### ISSUE TITLE
Support for Interrupt VM without panic

### ISSUE THREAD

**Issue by prsolucoes** [robertkrimen/otto#230]
Hi,

In my project:
https://github.com/prsolucoes/goci

I have added support to stop plugin execution. Everything is working fine on CLI and JS plugin.

The problem is when i stop the VM using Interrupt channel, i dont have another alternative of PANIC and it kill the host application and we need restart the server again and others execution is killed too.

Have any alternative to this behaviour?

Line:
https://github.com/prsolucoes/goci/blob/master/models/domain/plugin_js.go#L284

**Comment by darkliquid** [comment]
Couldn't you just do a `recover` around the parts of your app that are actually executing the vm? That way you can catch the panic, check the message and fail gracefully instead.

**Comment by prsolucoes** [comment]
Hi,

Do you have any example?

Thanks.

**Comment by darkliquid** [comment]
Check out these:

 * https://blog.golang.org/defer-panic-and-recover 
 * https://github.com/golang/go/wiki/PanicAndRecover

**Comment by dhiltonp** [comment]
I suspect you're looking in the wrong place for the bug.

Code like this works for me; feel free to give it a try.

    func (this *PluginJS) Stop(message string) {
        if this.vm.Interrupt != nil {
            this.vm.Interrupt <- func() {
                panic(this.vm.MakeCustomError("", fmt.Sprintf("Line %d: %s", col.vm.Context().Line, message)))
            }
            close(col.vm.Interrupt)
            col.vm.Interrupt = nil
        }
    }

If it doesn't work, please post the exact error you are seeing on the command line.

**Comment by prsolucoes** [comment]
First of all, i created it based on README example of otto:

```
func (This *PluginJS) Stop() error {
	This.Job.LogError(OG_CONSOLE, "Job stopped by the user")
	This.Job.UpdateDuration()
	This.Job.Status = JOB_STATUS_ERROR
	This.Job.Save()

	if caught := recover(); caught != nil {
		if caught == "Stopped by the user" {
			util.Debug("Stopped by the user")
		} else {
			panic(caught)
		}
	}

	if This.cmd != nil && This.cmd.Process != nil {
		This.cmd.Process.Kill()
	}

	if This.vm.Interrupt != nil {
		go func() {
			This.vm.Interrupt <- func() {
				panic(errors.New("Stopped by the user"))
			}
		}()
	}

	return nil
}

```

But it panic, stop the VM and stop the host program :(

After i used @dhiltonp code:

```
func (This *PluginJS) Stop() error {
	This.Job.LogError(OG_CONSOLE, "Job stopped by the user")
	This.Job.UpdateDuration()
	This.Job.Status = JOB_STATUS_ERROR
	This.Job.Save()

	if This.cmd != nil && This.cmd.Process != nil {
		This.cmd.Process.Kill()
	}

	if This.vm.Interrupt != nil {
		This.vm.Interrupt <- func() {
			panic(This.vm.MakeCustomError("", fmt.Sprintf("Line %d: %s", This.vm.Context().Line, "Stopped by the user")))
		}
		close(This.vm.Interrupt)
		This.vm.Interrupt = nil
	}

	return nil
}
```

But it dont stop the VM and it still running :(

**Comment by prsolucoes** [comment]
My log using first example:

```
New job started: [b7de43fd-aa84-11e6-be60-60f81daef1e6]
panic: Stopped by the user [recovered]
	panic: Stopped by the user

goroutine 34 [running]:
panic(0x4fa340, 0xc42021d9c0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/robertkrimen/otto.catchPanic.func1(0xc4206efc10)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/error.go:247 +0x3ec
panic(0x4fa340, 0xc42021d9c0)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/prsolucoes/goci/models/domain.(*PluginJS).Stop.func1.1()
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/models/domain/plugin_js.go:306 +0x84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc4201b6000, 0x82f620, 0xc420138ac0, 0x0, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:19 +0x14fd
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeForStatement(0xc4201b6000, 0xc420214140, 0xc420229e60, 0xc41ffe7a00, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:263 +0x1a1
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc4201b6000, 0x82f6a0, 0xc420214140, 0x0, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:68 +0x13e5
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc4201b6000, 0xc420329260, 0x3, 0x3, 0xc420659bb0, 0x28fd3, 0xc420659b80)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x75
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc4201b6000, 0xc42013a2a0, 0xc420659b00, 0x0, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0xf2
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/runtime.go:639 +0x44
github.com/robertkrimen/otto.catchPanic(0xc4206efc78, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/error.go:250 +0x6c
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc4201b6000, 0x4dcf80, 0xc42021d9e0, 0x0, 0x0, 0x43300, 0xb00000, 0x0, 0xa2, 0xc4200a2370, ...)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/runtime.go:640 +0x100
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc4201b6000, 0x4dcf80, 0xc42021d9e0, 0x0, 0x0, 0xc420659d48, 0xdadb, 0x4dcf80, 0xc42021d9e0, 0xc420659e28)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/runtime.go:651 +0x62
github.com/robertkrimen/otto.Otto.Run(0xc420229e60, 0xc4201b6000, 0x4dcf80, 0xc42021d9e0, 0xc42021d9e0, 0xa2, 0x0, 0xc420088200, 0x71)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/otto.go:295 +0x55
github.com/prsolucoes/goci/models/domain.(*PluginJS).Process(0xc420218000, 0xc4201fa900, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/models/domain/plugin_js.go:79 +0x541
github.com/prsolucoes/goci/models/domain.(*Job).Run(0xc42021f080)
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/models/domain/job.go:136 +0x197
github.com/prsolucoes/goci/jobs.StartJobProcessor.func1.1(0xc42021f080)
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/jobs/jobs.go:27 +0x32
created by github.com/prsolucoes/goci/jobs.StartJobProcessor.func1
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/jobs/jobs.go:50 +0xd0
```

**Comment by dhiltonp** [comment]
What happens when you run this code? Please show the output.

(I've removed the recover that wasn't in a defer, and removed the excess goroutine which indicates you personally are panicking and don't know what to do).

    func (This *PluginJS) Stop() error {
        This.Job.LogError(OG_CONSOLE, "Job stopped by the user")
        This.Job.UpdateDuration()
        This.Job.Status = JOB_STATUS_ERROR
        This.Job.Save()
    
        if This.cmd != nil && This.cmd.Process != nil {
            This.cmd.Process.Kill()
        }
    
        if This.vm.Interrupt != nil {
                This.vm.Interrupt <- func() {
                    panic(errors.New("Stopped by the user"))
                }
        }
    
        return nil
    }

**Comment by prsolucoes** [comment]
Ok, your code is the official stop function without modification:


After execute it, i got it on output:


```
paulo@MacBook-Pro-de-Paulo:~/Developer/workspaces/go/src/github.com/prsolucoes/goci (master) $ go install
paulo@MacBook-Pro-de-Paulo:~/Developer/workspaces/go/src/github.com/prsolucoes/goci (master) $ goci -f ~/Developer/goci/sample/config.ini 
Configuration file load : OK
Integrations : OK
Structure created on /Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/extras/sample : OK
Router creation : OK
Plugins : OK
APIController register : OK
Job processor stated : OK
Open GoCI on your browser: :8080
> New job started: [9daa1b1b-aa88-11e6-9009-60f81daef1e6]
panic: Stopped by the user [recovered]
	panic: Stopped by the user

goroutine 20 [running]:
panic(0x4fa140, 0xc420076330)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/robertkrimen/otto.catchPanic.func1(0xc42004fc10)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/error.go:247 +0x3ec
panic(0x4fa140, 0xc420076330)
	/usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:458 +0x243
github.com/prsolucoes/goci/models/domain.(*PluginJS).Stop.func1()
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/models/domain/plugin_js.go:296 +0x84
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc420250000, 0x82f620, 0xc42022f7b0, 0x0, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:19 +0x14fd
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeForStatement(0xc420250000, 0xc420016280, 0xc420019e60, 0xc41ffff600, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:263 +0x1a1
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc420250000, 0x82f6a0, 0xc420016280, 0x0, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:68 +0x13e5
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc420250000, 0xc420234000, 0x3, 0x3, 0xc4201adbb0, 0x28fd3, 0xc4201adb80)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate_statement.go:121 +0x75
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc420250000, 0xc4202121c0, 0xc4201adb00, 0x0, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:17 +0xf2
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/runtime.go:639 +0x44
github.com/robertkrimen/otto.catchPanic(0xc42004fc78, 0x0, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/error.go:250 +0x6c
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc420250000, 0x4dcd80, 0xc42022ec90, 0x0, 0x0, 0x43300, 0xb004b0, 0x0, 0xa2, 0xc4201be000, ...)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/runtime.go:640 +0x100
github.com/robertkrimen/otto.(*_runtime).cmpl_run(0xc420250000, 0x4dcd80, 0xc42022ec90, 0x0, 0x0, 0xc4201add48, 0xdadb, 0x4dcd80, 0xc42022ec90, 0xc4201ade28)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/runtime.go:651 +0x62
github.com/robertkrimen/otto.Otto.Run(0xc420019e60, 0xc420250000, 0x4dcd80, 0xc42022ec90, 0xc42022ec90, 0xa2, 0x0, 0xc420168080, 0x71)
	/Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/otto.go:295 +0x55
github.com/prsolucoes/goci/models/domain.(*PluginJS).Process(0xc42024c000, 0xc42024e380, 0x0)
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/models/domain/plugin_js.go:79 +0x541
github.com/prsolucoes/goci/models/domain.(*Job).Run(0xc420312000)
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/models/domain/job.go:136 +0x197
github.com/prsolucoes/goci/jobs.StartJobProcessor.func1.1(0xc420312000)
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/jobs/jobs.go:27 +0x32
created by github.com/prsolucoes/goci/jobs.StartJobProcessor.func1
	/Users/paulo/Developer/workspaces/go/src/github.com/prsolucoes/goci/jobs/jobs.go:50 +0xd0
```

**Comment by dhiltonp** [comment]
github.com/robertkrimen/otto.catchPanic.func1(0xc42004fc10)
        /Users/paulo/Developer/workspaces/go/src/github.com/robertkrimen/otto/error.go:247 +0x3ec

The panic is coming from error.go:247, so let's look there:
https://github.com/robertkrimen/otto/blob/master/error.go#L223

What do you notice about the logic flow necessary for this panic to occur?

**Comment by prsolucoes** [comment]
Hi

This is the steps to reproduce it:

1. go get -u github.com/prsolucoes/goci
2. echo -e "[server]\nhost = 8080\nworkspaceDir = $GOPATH/src/github.com/prsolucoes/goci/extras/sample" > /tmp/config.ini
2. goci -f /tmp/config.ini
3. open http://localhost:8080/task/view/my-project/task-long-running-js
4. click on button "RUN"
5. click on button "STOP"
6. PÃM!

What is happening on the JS file when we stop?
> https://github.com/prsolucoes/goci/blob/master/extras/sample/scripts/task-long-running-js.js

We can call STOP on other task that dont use otto and it works without problem:
> http://localhost:8080/task/view/my-project/task-long-running-cli

**Comment by dhiltonp** [comment]
I'm afk for now, you're on your own for the next several hours at least. I
should have more time in about 20 hours.

**Comment by prsolucoes** [comment]
Ok, no problem. Thank you for any help :)

**Comment by dhiltonp** [comment]
So no, that's not what I meant to ask.

If you look at otto's error.go (where the actual panic occurs) what do you see? What logic flow in that function causes an exception to be raised on line 247?

**Comment by dhiltonp** [comment]
FWIW, I know exactly what is wrong with your code, I'm trying to walk you through to the solution in a way that will help you in the future.

**Comment by prsolucoes** [comment]
Hi,

Did you find any solution?

Thanks.

**Comment by linkerlin** [comment]
run plugins in a seperated procress.

**Comment by prsolucoes** [comment]
But how?

**Comment by dhiltonp** [comment]
You need to properly throw and catch an exception.

Your custom exception doesn't work because your if statement is doing the
wrong comparison.

You can instead use one of Ottos exceptions and it will automatically be
caught, but there was a one line error in the sample I gave you - actually,
not an error so much as an incompatibility with what you were doing
elsewhere, but I can't remember what.

This is from memory, as I haven't looked at it in 1.5 months and I'm
traveling.

I cannot give you more precise advice at this time (afk for at least 1
month), but every iteration of code I've seen you run is about 1 line away
from working.

It's a matter of debugging - looking at the line in the stack trace and
examining the relevant variable, seeing how it differs from what you
expect, then either making it look correct where it is generated, or
altering your expectations/comparisons.

I've given you specific lines to look at to help you think about what you
should expect.

Good luck!

On Jan 3, 2017 9:37 PM, "prsolucoes" <notifications@github.com> wrote:

But how?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/robertkrimen/otto/issues/230#issuecomment-270293233>,
or mute the thread

**Comment by prsolucoes** [comment]
When you can, you can help me?

Today is:

```
func (This *PluginJS) Stop() error {
	This.Job.LogError(OG_CONSOLE, "Job stopped by the user")
	This.Job.UpdateDuration()
	This.Job.Status = JOB_STATUS_ERROR
	This.Job.Save()

	if This.cmd != nil && This.cmd.Process != nil {
		This.cmd.Process.Kill()
	}

	if This.vm.Interrupt != nil {
		This.vm.Interrupt <- func() {
			panic(errors.New("Stopped by the user"))
		}
	}

	return nil
}
```

**Comment by prsolucoes** [comment]
I solved the problem. After read the interrupt example, i see that put on wrong place. I need put it before RUN the code. And the halt is a property to be compared with the error sent to interrupt channel.

Thanks.
