### ISSUE TITLE
TypeError when using splice

### ISSUE THREAD

**Issue by tienthanh1993** [robertkrimen/otto#234]
i'm trying to run script splice an array, but it gives me TypeError in this case 
```
hashStr = "6E6E6EF72905D973E8FEF9F38F01AC4D95A600E6A6E1.C1DBF2F71A5F8C9EB04B75E7A879B4C90C25313A";
hashArr=hashStr.split("");
hashArr.splice(0,2); // error at here
```

another test work fine 
` ["1","2","3"].splice(0,2);`

**Comment by robertkrimen** [comment]
Looks like this change was the cause: 7427d59

@dhiltonp

**Comment by dhiltonp** [comment]
You want to take care of #225 while you're at it?
