### ISSUE TITLE
Any good database libraries for integrating into otto?

### ISSUE THREAD

**Issue by handicraftsman** [robertkrimen/otto#237]
I am writing an IRC bot with otto-powered plugin system. Now i need any way of storing data (for example, database) to store stuff like permissions. Any db-libraries which can be easily embedded into otto?

**Comment by darkliquid** [comment]
Well it depends on what you want, but assuming you want to embed a db engine into the go part of the app and just expose it to the otto runtime, if all you need is simple key-store access, writing a thin wrapper around something like boltdb might be a way to go.

**Comment by handicraftsman** [comment]
@darkliquid, that's nice! Thanks!
