### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by beatscode** [robertkrimen/otto#240]
I am trying to convert some code and get the string representation of the conversion.  Is there any way to run a script, alter properties/values and get the altered source code?

**Comment by deoxxa** [comment]
Short answer: nope!

Longer (and more useful) answer: nope, for a couple of reasons:

1. changing the values of variables that arise from running some code doesn't change the original source. This is true of every JavaScript engine I can think of.
2. otto doesn't have a way to turn an AST back into source text.

You could potentially use otto's parser to read your JavaScript source, then modify the AST, then walk the AST, printing each node as its equivalent text. Indeed this is how most pretty-printers (e.g. `gofmt`) work. You'd have to implement the printing part though, as that's not a feature of otto.
