### ISSUE TITLE
How costly is passing an object between the go-javascript interface?

### ISSUE THREAD

**Issue by cesarsalgado** [robertkrimen/otto#243]
I tried to understand the code, but I couldn't figure out.

I made some tests and notice that if I change a value inside javascript of a struct passed by address to otto.Call then the change will also be seen in the go. So this makes me think that the objects aren't copied when passed by reference. But I conjecture that otto must build some wrapper object around the original go object. But I am not sure if it does that but traversing deeply all the elements in a struct/slice /map at the beginning or if the wrapper is created just when some access is needed (lazily) on the javascript side.

Some more specific questions: Does the overhead of passing an slice to otto increases with the size of the slice? What about increasing the size of map passed by reference? What about a struct?

Regards

**Comment by leromarinvit** [comment]
There is no deep-copying being done, all values are lazily accessed via reflect only when needed.

(I'm not the author, but I've done a bit of work on otto.)
