### ISSUE TITLE
'Call' within go routine cause concurrent map read and map write

### ISSUE THREAD

**Issue by guptasu** [robertkrimen/otto#246]
I want to measure timings on concurrent calls to js methods from go.
Here is my code. This code seems so simple and I am not expecting any sharing of go objects.

Any idea why I am getting "fatal error: concurrent map writes" (call stack below). Seems like there is some shared map in the VM that is manipulated across context for every js function is invocation.

How to fix/workaround this issue and not affect the performance.. I know copy of the context might work, but that will be slow.

Is this a bug or my code is wrong ?

```
package main
import "testing"
import (
	"github.com/robertkrimen/otto"
)
func BenchmarkPractice(b *testing.B) {
	vm2 := otto.New()
	vm2.Run(`
		function one() {}
		function two() {}
		function three() {}
		function four() {}
		function five() {}
	`)
	methodsToInvoke := []string{"one","two","three","four","five",}
	for n := 0; n < b.N; n++ {
		done := make(chan bool)
		for _, fName := range methodsToInvoke {
			fn, _ := vm2.Get(fName)
			go func() {
				fn.Call(otto.NullValue())
				done <- true
			}()
		}

		for i := 0; i < len(methodsToInvoke); i++ {
			<-done
		}
	}
}
```

p.s.
call stack:

fatal error: concurrent map writes

goroutine 44 [running]:

runtime.throw(0x12c3f4f, 0x15)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc4201a57b0 sp=0xc4201a5790
runtime.mapassign(0x127f9e0, 0xc420192270, 0xc4201a5888, 0x9)
	/usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc4201a5850 sp=0xc4201a57b0
github.com/robertkrimen/otto.(*_dclStash).createBinding(0xc420192240, 0x12c0ad2, 0x9, 0x0, 0x5, 0x12b5b60, 0xc420196120)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/stash.go:172 +0xa8 fp=0xc4201a58c8 sp=0xc4201a5850
github.com/robertkrimen/otto.(*_dclStash).setValue(0xc420192240, 0x12c0ad2, 0x9, 0x5, 0x12b5b60, 0xc420196120, 0x0)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/stash.go:195 +0xf4 fp=0xc4201a5910 sp=0xc4201a58c8
github.com/robertkrimen/otto.(*_runtime).cmpl_call_nodeFunction(0xc42007e000, 0xc42000f800, 0xc420192240, 0xc4200b2380, 0x1, 0x0, 0x0, 0x14ad0e8, 0x0, 0x0, ...)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/cmpl_evaluate.go:48 +0x423 fp=0xc4201a59d8 sp=0xc4201a5910
github.com/robertkrimen/otto.(*_object).call(0xc42000f800, 0x1, 0x0, 0x0, 0x14ad0e8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/type_function.go:178 +0x9b8 fp=0xc4201a5d48 sp=0xc4201a59d8
github.com/robertkrimen/otto.Value.call(0x5, 0x12b5b60, 0xc42000f800, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/value.go:123 +0x122 fp=0xc4201a5e08 sp=0xc4201a5d48
github.com/robertkrimen/otto.Value.Call.func1()
	/Users/guptasu/go/src/github.com/robertkrimen/otto/value.go:112 +0x8b fp=0xc4201a5e88 sp=0xc4201a5e08
github.com/robertkrimen/otto.catchPanic(0xc420090ee0, 0x0, 0x0)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/error.go:250 +0x6c fp=0xc4201a5eb0 sp=0xc4201a5e88
github.com/robertkrimen/otto.Value.Call(0x5, 0x12b5b60, 0xc42000f800, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14ad120, ...)
	/Users/guptasu/go/src/github.com/robertkrimen/otto/value.go:113 +0xe2 fp=0xc4201a5f38 sp=0xc4201a5eb0
github.com/guptasu/perfotto.BenchmarkPractice.func1(0x5, 0x12b5b60, 0xc42000f800, 0xc420196060)
	/Users/guptasu/go/src/github.com/guptasu/perfotto/practice_test.go:21 +0x8e fp=0xc4201a5fc0 sp=0xc4201a5f38

**Comment by guptasu** [comment]
Adding @geeknoid

**Comment by prsolucoes** [comment]
You can use this thread-safe list:

https://github.com/prsolucoes/gotslist

**Comment by guptasu** [comment]
Friendly ping

**Comment by stevenh** [comment]
It may not be clear initially but as with all go unless it's explicitly stated go code / libraries are not multiple go routine safe.

An otto is one of those libraries where an instance is not go routine safe, so this is to be expected I'm afraid.

**Comment by guptasu** [comment]
Hi Steven @stevenh , Is there other recommended way of invoking JS methods in parallel via Otto ?

**Comment by deoxxa** [comment]
@guptasu you really only have two options.

1. synchronise access to the interpreter (via a lock or a channel), or
2. use multiple interpreters, one per goroutine (obviously not shared)

**Comment by stevenh** [comment]
Exactly as @deoxxa details @guptasu

**Comment by seregayoga** [comment]
@deoxxa maybe add mention about this issue to the readme? Something like `Be careful. Library isn't thread-safe.`

**Comment by stevenh** [comment]
While this may sound like a good idea if every library which wasn’t this would be everywhere.
It’s generally accepted that unless the inverse is stated (the library is thread safe) that it isn’t, this goes for the main go libraries in the core runtime too.
Given this me preference would be to not add this.
