### ISSUE TITLE
console.dir(object)

### ISSUE THREAD

**Issue by neopaf** [robertkrimen/otto#247]
please consider adding [`console.dir(object)`](https://developer.mozilla.org/en-US/docs/Web/API/Console/dir)

to be an alias to 
```
console.log(JSON.stringify(object))
```

this would allow people to use same JavaScript code both
* through otto (thanks for this cool project!)
* in web-browser (where complex data structures are very conveniently displayed, parts are foldable and so on)

**Comment by neopaf** [comment]
I came from [here](https://github.com/couchbase/sync_gateway/issues/2487) with this.

otto tracking issue is [here](https://github.com/couchbase/sync_gateway/issues/2471).

**Comment by mleonard87** [comment]
Given that the MDN says this is not a standard is seems like a bad idea to add it to Otto itself. However, to make your code work you can easily add this:

```golang
vm := otto.New()
_, err := vm.Run(`
    console.dir = function(obj) {
        console.log(JSON.stringify(obj));
    }
)
```

**Comment by deoxxa** [comment]
+1 to redefining it in the application.

It's super simple to do it that way, and means you can choose what the most appropriate behaviour is for couchbase's sync gateway. Maybe you want to log JSON as one line (simple `JSON.stringify`), maybe you want it to be multiple lines (e.g. `JSON.stringify(obj, null, 2)`), maybe you'll find something even better.

There's some precedent for this approach, by the way: #260, #209, #171, #150 - similar advice each time.
