### ISSUE TITLE
can't  pass javascript function to golang function

### ISSUE THREAD

**Issue by jetgeng** [robertkrimen/otto#253]
i have a function write in golang named MulitMerge as follow:

```golang
func MulitMerge(callBack interface{}) {
	fmt.Println(reflect.TypeOf(callBack))
}

```
i want to use it in javascript , so i write some code as follow:

```golang
   vm := otto.New()
   vm.Set("muliMerge", MulitMerge)
   vm.Run(`
        muliMerge(function(){
              console.log(" i am in callback function") 
        })
  `
```
i can't get the " i am in callback function" in terminal. just get  "map[string]interface {}" print by MulitMerge function which written in golang. and the map is empty! my question is how to call the give callback function? 

thanks!

**Comment by lycis** [comment]
If you define `MultiMerge` like this it should work (at least it does in my applications):

```go
func MultiMerge(callBack otto.Value)
```

You can e.g. resolve the value and run it, if it is a java script function:

```go
func MulitMerge(callBack otto.Value) {
	fmt.Println(reflect.TypeOf(callBack))
	if callBack.IsFunction() {
		callBack.Call(otto.UndefinedValue())
	}
}
```

**Comment by deoxxa** [comment]
You have to make sure your callback function has a useful type signature.

```go
package main

import (
	"fmt"

	"github.com/robertkrimen/otto"
)

func MultiMerge(callback func()) {
	fmt.Printf("before callback\n")
	callback()
	fmt.Printf("after callback\n")
}

func main() {
	vm := otto.New()
	vm.Set("MultiMerge", MultiMerge)
	vm.Run("MultiMerge(function() { console.log('inside callback'); })")
}
```
