### ISSUE TITLE
Redirecting console.log output

### ISSUE THREAD

**Issue by mleonard87** [robertkrimen/otto#260]
By default invoking console.log() inside of an otto VM write the output to stdout notably via [fmt.Fprintln(os.Stdout, ...)](https://github.com/robertkrimen/otto/blob/master/console.go#L18) from what I can see.

Is it possible to direct this somewhere else? For example by substituting this for something that implements io.Writer?

**Comment by darkliquid** [comment]
You can always define a function in Go to do what you want, than assign the function to console.log in javascript.

**Comment by mleonard87** [comment]
Thanks!

I can't seem to set it directly with `vm.Set("console.log", func ...)` But the following works:

```go
vm.Set("__log__", func(call otto.FunctionCall) otto.Value {
    m := ""
    for _, v := range call.ArgumentList {
        m = fmt.Sprintf("%s %s", m, v.String())
    }
    // Do what you want with the console output...
    return otto.Value{}
})

vm.Run("console.log = __log__;")
```
