### ISSUE TITLE
Date parsing returns wrong time

### ISSUE THREAD

**Issue by shashanktomar** [robertkrimen/otto#264]
I am not sure if I am missing something obvious here:

This code in golang via otto returns: **1500544757569** though the same in [js](https://jsfiddle.net/xu0mf0mk/) returns **1500544757570** 

Golang code:
```
package main
import "github.com/robertkrimen/otto"
func main() {
  vm := otto.New()
  vm.Run(`
      var time = new Date("2017-07-20T09:59:17.570Z").getTime();
      console.log("Time for 2017-07-20T09:59:17.570Z is " + time);
  `)
}
```

Javascript [code](https://jsfiddle.net/xu0mf0mk/)
`console.log(new Date("2017-07-20T09:59:17.570Z").getTime())`

**Comment by stevenh** [comment]
Confirmed this is now working
