### ISSUE TITLE
reference error line numbers? 

### ISSUE THREAD

**Issue by Ashtonian** [robertkrimen/otto#265]
When getting a reference error from Otto - line numbers are not provided. Line numbers are provided for other errors. It looks like this is for errors that are [caught](https://github.com/robertkrimen/otto/blob/master/error.go#L233) in the vm rather then parse errors.  `_at` is set correctly and `location()` works internally. It looks like the `.Error()` calls `.Format()` instead of `.formatWithStack()`. Is that correct behavior and is there any chance we can make that configurable? 

Repro: 
```go
vm := otto.New()
_, err := vm.Run(`
	var x = 5 
	if ( somethingUndefined ) {
		x = 2 
	}
`)
log.Println(err) // no line numbers :( 
```

As a hopefully temp workaround I've type asserted the err as an Otto error and am able to access the `.String()`. 

Workaround: 
```go
if err != nil {
  if ottoError, ok := err.(*otto.Error); ok {
    log.Println(ottoError.String()) //  line numbers 
  }     
}
```

**Comment by stevenh** [comment]
You can do this with `log.Printf("%#v", err)`
