### ISSUE TITLE
Single array values bad casting?

### ISSUE THREAD

**Issue by toomuchio** [robertkrimen/otto#269]
So not sure if I'm doing something wrong here but this is quite odd:

go:
```
func () Blah(call otto.FunctionCall) otto.Value {
	raw, err := call.Argument(0).Export()
	actual, ok := raw.([]interface{})
	if !ok {
		return 0
	}
}
```
JS:
```
 x = 3;
blah([x]); < Fails with return 0

blah([x,1]) < Works
```
This did work at a certain point in time with otto as the code I'm using is unchanged form 2015 era having recompiled it today for the first time in a long time, I'm having issues.

**Comment by deoxxa** [comment]
`Export()` now tries to export to a more specific slice type if it can, e.g. `[]int` or `[]string`. You should check what the actual exported value is.

**Comment by toomuchio** [comment]
@deoxxa 

That seems nonsensical, I'm checking if Argument 0 is an array right.

You're telling me since it only contains a single value it could be casted as just an int or string?

It doesn't explain why blah([1,1]) works as intended and blah([1]) doesn't, both should return an array.

**Comment by deoxxa** [comment]
I wrote this test just now, and it passes. Can you modify it so that it fails and demonstrates the issue you're talking about?

```go
		// issue #269
		{
			called := false
			vm.Set("blah", func(c FunctionCall) Value {
				v, err := c.Argument(0).Export()
				is(err, nil)
				is(v, []int64{3})
				called = true
				return UndefinedValue()
			})
			is(called, false)
			test(`var x = 3; blah([x])`)
			is(called, true)
		}
```

**Comment by deoxxa** [comment]
You can put that test in `reflect_test.go`, by the way.

**Comment by stevenh** [comment]
Feedback timeout
