### ISSUE TITLE
Function.caller ?

### ISSUE THREAD

**Issue by shithappens2016** [robertkrimen/otto#270]
please implement **Function**._caller_

**Comment by deoxxa** [comment]
Please try out #275 :)

**Comment by alexandrugrigor** [comment]
After #275 seems that the following does not correctly work anymore:
```    
vm := otto.New()
val, err := vm.Eval("(function(stringValue){ return stringValue.startsWith('Hello');})('Hello world!')")
fmt.Println(val)
fmt.Println(err)
```
an error with the following message now appears: TypeError: 'startsWith' is not a function.
Not sure if #275 is the problem but it stopped working after last updated

**Comment by deoxxa** [comment]
Otto doesn't implement `startsWith`, and never has... That would have never worked anyway.

**Comment by shithappens2016** [comment]
great
