### ISSUE TITLE
panic - Mixed type array gives panic on export

### ISSUE THREAD

**Issue by MichaelS11** [robertkrimen/otto#279]
```Go
package main

import (
	"fmt"
	"github.com/robertkrimen/otto"
)

func main() {

	vm := otto.New()

	_, err := vm.Run(`
var output = [[1,2.1], [3, 4]];
	`)

	if err != nil {
		fmt.Println(err)
		return
	}

	outputValue, err := vm.Get("output")
	if err != nil {
		fmt.Println(err)
		return
	}

	outputInterface, _ := outputValue.Export()

	fmt.Println(outputInterface)
}
```

Panic:

> panic: reflect.Set: value of type []interface {} is not assignable to type []int64
> 
> goroutine 1 [running]:
> reflect.Value.assignTo(0x671a80, 0xc0420fd8c0, 0x97, 0x6bedd6, 0xb, 0x671a00, 0x0, 0x0, 0x671a80, 0xc0420fd8c0)
> 	C:/app/Go/src/reflect/value.go:2181 +0x30e
> reflect.Value.Set(0x671a00, 0xc0420efda0, 0x197, 0x671a80, 0xc0420fd8c0, 0x97)
> 	C:/app/Go/src/reflect/value.go:1351 +0xab
> vendor/github.com/robertkrimen/otto.Value.export(0x5, 0x6b4020, 0xc0420f9aa0, 0x0, 0x0)
> 	C:/Users/username/Documents/Eclipse/src/vendor/github.com/robertkrimen/otto/value.go:718 +0xe9f
> vendor/github.com/robertkrimen/otto.Value.Export(0x5, 0x6b4020, 0xc0420f9aa0, 0x0, 0x0, 0x0, 0x0)
> 	C:/Users/username/Documents/Eclipse/src/vendor/github.com/robertkrimen/otto/value.go:648 +0x6e
> main.main()
> 	C:/Users/username/Documents/Eclipse/src/test/main.go:27 +0x344
>

**Comment by buchanae** [comment]
Related to this is that `Export` may return a variety of slice types. The docs on `Export` say that an `Array` is always cast to `[]interface{}`. I think it's more consistent and easier to program against `Export` if it always returns `[]interface{}`

**Comment by elakito** [comment]
It seems the export works when you have an array of mixed types or having some null but not with an array of values of the same derived type. 
```
var val1 = [
    [true, null, 64],
    [null, 32, null]
];

var val2 = [
     ["myboolean", "myint", "mylong"],
     [null, 32, null]
]; 
```

`var1` can be exported but exporting `var2` will results in

```
panic: reflect.Set: value of type []string is not assignable to type []interface {}

goroutine 1 [running]:
reflect.Value.assignTo(0x1205f80, 0xc0001257a0, 0x97, 0x1252859, 0xb, 0x1205400, 0x0, 0x2, 0xc00012a1b0, 0xc000125940)
	/usr/local/opt/go/src/reflect/value.go:2269 +0x44c
reflect.Value.Set(0x1205400, 0xc00012a1b0, 0x197, 0x1205f80, 0xc0001257a0, 0x97)
	/usr/local/opt/go/src/reflect/value.go:1403 +0xa7
github.com/robertkrimen/otto.Value.export(0x5, 0x1247c40, 0xc000119bc0, 0x4, 0xc000101e70)
	/Users/d025803/goworkspace/src/github.com/robertkrimen/otto/value.go:718 +0x656
github.com/robertkrimen/otto.Value.Export(0x5, 0x1247c40, 0xc000119bc0, 0x4, 0x5, 0x1247c40, 0xc000119bc0)
	/Users/d025803/goworkspace/src/github.com/robertkrimen/otto/value.go:648 +0x3f
```

**Comment by elakito** [comment]
@MichaelS11 why is this issue marked as closed?

**Comment by MichaelS11** [comment]
I am no longer activity using otto. Thank you kindly for fixing it. :)
