### ISSUE TITLE
Incorrect Implementation of Number.toLocaleString

### ISSUE THREAD

**Issue by omervk** [robertkrimen/otto#285]
```
// Current locale is en-US
1451.toLocaleString()
```

Expected: `1,451`
Actual: `1451`

```
1451.toLocaleString('en-US')
```

Expected: `1,451`
Actual: `RangeError: toString() radix must be between 2 and 36`

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by stevenh** [comment]
This would require [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl).

The two argument form is not supported in ES 5, hence the error you get.

With all that said number support is pretty trivial so I've implemented that in #472
