### ISSUE TITLE
How render a html strings?

### ISSUE THREAD

**Issue by vectorchen** [robertkrimen/otto#287]
eg.  there is a string content as follow,

![image](https://user-images.githubusercontent.com/14350150/35082209-80d28732-fc53-11e7-8df1-7d816719400d.png)

the result wanna get is as follow,
`<div>Hello, world!</div>`

**Comment by deoxxa** [comment]
Otto is a JavaScript interpreter, and nothing more. You'd need a [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model/Introduction) implementation bound to otto to do what you want.

**Comment by vectorchen** [comment]
@deoxxa Thank you for your tips !
