### ISSUE TITLE
ast.Walk doesn't actually walk the whole AST

### ISSUE THREAD

**Issue by nigeltao** [robertkrimen/otto#299]
When calling ast.Walk on an ast.DotExpression n, n.Left will be Walk'ed recursively, but n.Identifier will be ignored.

Similarly for ast.LabelledStatement, its Identifier will be ignored.

When calling ast.Walk on an ast.Program n, n.Body will be Walk'ed recursively, but n.DeclarationList will be ignored.

There may be more examples. I only did a quick skim of a few node types, after being surprised that calling ast.Walk with a visitor that type switched for ast.Identifier nodes didn't actually visit all ast.Identifier nodes.

**Comment by stevenh** [comment]
I fixed the two issues from this.

`DeclarationList` shouldn't be Walked as the nodes are already covered, they are really just a grouping.
