### ISSUE TITLE
What about Precompilering

### ISSUE THREAD

**Issue by Dorbmon** [robertkrimen/otto#301]
It is very useful to precomiler the JavaScript Code before run it.Maybe We know What will we use It to do.Can otto privide us with Precompiler,pls?

**Comment by dsamarin** [comment]
Would you like to submit a pull request for a JIT compiler backend?

**Comment by deoxxa** [comment]
I can't even figure out what this is about. Please rephrase, @Dorbmon.

**Comment by Dorbmon** [comment]
@dsamarin As your wish,we build a project called R.JS based OTTO,but we are still working on it.We may show it soon?

**Comment by stevenh** [comment]
While this would be nice I think it's a major undertaking, so if someone would like to submit a PR they are welcome but for now closing this.
