### ISSUE TITLE
mode StoreComments

### ISSUE THREAD

**Issue by exls** [robertkrimen/otto#303]
I have code to parse 
> `
> src := "
> 		//first
> 		//@name second
> 		/*		third*/
> 		bb=12;
> 		//blabla
> 		a = 1;
> 	"`

Result is:

> map[0xc42006a610:[Comment: first Comment: @name second Comment:                 third] 0xc42006a790:[Comment: blabla]]
> 
> 
> Output: bb = &{Name:bb Idx:45} (identifier) 0xc420076480
> Input: bb = &{Name:bb Idx:45} (identifier) 0xc420076480
> Output: a = &{Name:a Idx:65} (identifier) 0xc420076500
> Input: a = &{Name:a Idx:65} (identifier) 0xc420076500

I want to associate comments with expressions. I saw in the comments.go ability to do it, but how to receive it on the top level in ast.Program?! I think, in the CommentsMap the Node pointer should be expression pointer.

**Comment by stevenh** [comment]
The comments are associated with nodes you can see this from this little example test:
```go
func Test_issue303(t *testing.T) {
	src := `
		//first
		//@name second
		/* third*/
		bb=12;
		//blabla a = 1;`

	program, err := parser.ParseFile(nil, "", src, parser.StoreComments)
	require.NoError(t, err)

	for node, comments := range program.Comments {
		fmt.Printf("node: %T = %v\n", node, comments)
	}
}
```
Which outputs:
```shell
node: *ast.ExpressionStatement = [Comment: first Comment: @name second Comment:  third]
node: *ast.Program = [Comment: blabla a = 1;]
```
