### ISSUE TITLE
How do you get returned values?

### ISSUE THREAD

**Issue by sb10** [robertkrimen/otto#308]
I can use `value, err := vm.Run(e)` to get a value when e is something like:

```
$whatever = 16
```

But the following do not work:

```
var whatever = 16
```

```
return 16
```

That last one gives error `Illegal return statement`.

How are you supposed to evaluate arbitrary javascript expressions that return values?

**Comment by deoxxa** [comment]
Can you provide a full example that exhibits the problem you mention?

**Comment by sb10** [comment]
```
package main

import (
	"fmt"

	"github.com/robertkrimen/otto"
)

func main() {
	vm := otto.New()
	value, err := vm.Run("return 16")
	fmt.Printf("%+v, %s\n", value, err)
}
```

Results in:

> undefined, (anonymous): Line 1:1 Illegal return statement

Changing the string to `$s = 16` results in:

> 16, %!s(<nil>)

**Comment by deoxxa** [comment]
Right, so the problem there is that `return 16` is not a valid JavaScript program. At the top level, a `return` statement makes no sense, since you're not in a function to `return` _from_.

Try the same thing in your browser console and you'll get the same error.

**Comment by deoxxa** [comment]
Put it in a function. Something like `vm.Run("(function() { return 16; })()")`.
