### ISSUE TITLE
Go1.11beta1 causes builtinArray_indexOf to infinite loop

### ISSUE THREAD

**Issue by bbrks** [robertkrimen/otto#314]
`TestArray_indexOf` hangs indefinitely under Go 1.11beta1. I have tried bumping the test timeout up to rule out slow-running tests, but it just sits there indefinitely. I've narrowed it down to this specific test:
https://github.com/robertkrimen/otto/blob/15f95af6e78dcd2030d8195a138bd88d4f403546/array_test.go#L373-L377

Going a bit deeper, the for loop in `builtinArray_indexOf` seems to be stuck in an infinite loop. This issue has also been seen in a project which uses Otto, so it's not limited to the specific unit test mentioned.

https://github.com/robertkrimen/otto/blob/15f95af6e78dcd2030d8195a138bd88d4f403546/builtin_array.go#L488-L498

Digging even deeper, I think the root cause is a compiler optimisation bug. So I'll raise this issue for tracking purposes, and I filed a Go issue here: https://github.com/golang/go/issues/26194

**Comment by deoxxa** [comment]
Well that's pretty cool! I mean, bad, but still, cool! If I get some time later on I'll see if some gentle massaging (e.g. moving the `>= 0` condition) makes the compiler happy.

**Comment by bbrks** [comment]
Looks like it's fixed in Go tip, should be in beta2 once it's out.

**Comment by bbrks** [comment]
I don't see a reason to keep this open any more. Closing.
