### ISSUE TITLE
Does this support npm modules?

### ISSUE THREAD

**Issue by tamalsaha** [robertkrimen/otto#315]
Does this support npm modules? I would like to be able to organize my code in multiple modules. ES6 module syntax will be preferred form.

**Comment by Dorbmon** [comment]
No.

**Comment by deoxxa** [comment]
Not directly, no. You'd have to implement your own module loader to make it work - but even then you won't be able to load ES6 code, since otto only targets ES5.

**Comment by boolooper** [comment]
@tamalsaha  https://github.com/ddliu/motto this may help you. It provides module loaders.
