### ISSUE TITLE
Math.random() uses same seed every time

### ISSUE THREAD

**Issue by yungtravla** [robertkrimen/otto#316]
Hi,

Every time I call `Math.random()`, it gives me the same output.

Is there a way to manually set the seed?

**Comment by haroldrandom** [comment]
+1

**Comment by yungtravla** [comment]
You can create your own Otto function or you can achieve a pseudo random number with JS like this:

```js
math_seed = new Date().getMilliseconds()

function randomFloat() {
	r = Math.sin(math_seed++) * 10000
	return r - Math.floor(r)
}
```

It would be nice if the `Math.random()` function actually behaved like the JavaScript engine's instead of that of Golang.

**Comment by deoxxa** [comment]
https://godoc.org/github.com/robertkrimen/otto#Otto.SetRandomSource
