### ISSUE TITLE
float number precision lose.

### ISSUE THREAD

**Issue by mistyworm** [robertkrimen/otto#327]
var percent = 0.06;
var spread = 0.05;
var profitPercent = percent - spread;
console.log(profitPercent);   //0.009999999999999995

**Comment by Webern** [comment]
Node.js does the same, not a bug but expected floating precision drift.

![image](https://user-images.githubusercontent.com/6260372/47336183-76dabe00-d643-11e8-8558-13fb66f286a8.png)
