### ISSUE TITLE
builtin_string.go and builtin_unescape issues

### ISSUE THREAD

**Issue by jkingben** [robertkrimen/otto#332]
some methods in builtin_string.go (such as: indexOf, substring) processing should be converted to [] rune, because there will be garbled characters in Asian characters according to the current processing method (an asian character occupies 3 bytes in length).
for example: "中abc" string. the index returned by indexOf("a") is 3.  substring(0, 1) returns garbled code

unescape ("中abs") is also the same garbled string returned

**Comment by stevenh** [comment]
This should be fixed by: https://github.com/robertkrimen/otto/pull/450
