### ISSUE TITLE
I want know why result is so?

### ISSUE THREAD

**Issue by beanhacker** [robertkrimen/otto#347]
when i run the test demo, get a 2^5 result from vm and go,
i find the vm is more faster than go itself,so can not understand.
js is slower than go,but here is faster, i want know why?

C:\Users\Administrator\Desktop\test\otto>otto.exe
The value of abc is 32
js cost time: 0s
[otto.zip](https://github.com/robertkrimen/otto/files/3219645/otto.zip)

The value of abc is 32
go cost time: 5.0003ms

C:\Users\Administrator\Desktop\test\otto>otto.exe
The value of abc is 32
js cost time: 0s
The value of abc is 32
go cost time: 10.0006ms

C:\Users\Administrator\Desktop\test\otto>otto.exe
The value of abc is 32
js cost time: 1ms
The value of abc is 32
go cost time: 4.0002ms

C:\Users\Administrator\Desktop\test\otto>otto.exe
The value of abc is 32
js cost time: 2.0002ms
The value of abc is 32
go cost time: 2.0001ms

C:\Users\Administrator\Desktop\test\otto>otto.exe
The value of abc is 32
js cost time: 0s

The value of abc is 32
go cost time: 11.0007ms

**Comment by stevenh** [comment]
No idea what your code is doing be could well be timing inaccuracies based on the fact you have some zeros in your results

**Comment by Asday** [comment]
```go
package main

import (
	"fmt"
	"math"
	"time"

	"github.com/robertkrimen/otto"
)

func main() {
	vm := otto.New()
	t := time.Now()
	vm.Run(`
	    abc =Math.pow(2, 5);
	`)
	value, _ := vm.Get("abc")
	fmt.Println(fmt.Sprintf("The value of abc is %v", value))
	fmt.Println(fmt.Sprintf("js cost time: %v", time.Now().Sub(t)))

	t1 := time.Now()
	fmt.Println(fmt.Sprintf("The value of abc is %v", math.Pow(2, 5)))
	fmt.Println(fmt.Sprintf("go cost time: %v", time.Now().Sub(t1)))

}
```

That's his code, from the zip file.

**Comment by stevenh** [comment]
The one-off run like this is unlikely to give you good quality results, in addition to this you're likely benchmarking `fmt.Println` as much as the maths function.

You will get better results using a benchmark test. When doing this be careful to store the result otherwise the compiler may optimise out your code.

Do be aware that otto is definitely known to be much slower than native JS engines.
