### ISSUE TITLE
nonsupport let 

### ISSUE THREAD

**Issue by binbin0325** [robertkrimen/otto#350]
When there is a let variable in my js code,otto will report an error。I wonder if otto does not support let
![image](https://user-images.githubusercontent.com/28588342/60252631-2962cf00-98fd-11e9-9981-36d8851a8800.png)

![image](https://user-images.githubusercontent.com/28588342/60252700-4ac3bb00-98fd-11e9-8876-ed0c40e13e3f.png)

**Comment by Asday** [comment]
https://github.com/robertkrimen/otto#caveat-emptor

> * Otto targets ES5. ES6 features (eg: Typed Arrays) are not supported.
