### ISSUE TITLE
JavaScript btoa and atob functions are missing

### ISSUE THREAD

**Issue by niondir** [robertkrimen/otto#354]
Is it planned to implement the `btoa` and `atob` functions in Otto?

See: https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding

**Comment by Asday** [comment]
https://www.ecma-international.org/ecma-262/5.1/

Doesn't appear to be part of ECMAscript 5.  (I could be looking in the wrong place, though).

**Comment by Niondir** [comment]
Okay and if someone is missing this, the following works fine for me.

```
func jsBtoa(b string) string {
	return base64.StdEncoding.EncodeToString([]byte(b))
}

func jsAtob(str string) string {
	b, err := base64.StdEncoding.DecodeString(str)
	if err != nil {
		v, _ := otto.ToValue("Failed to execute 'jsAtob': The string to be decoded is not correctly encoded.")
		panic(v)
	}
	return string(b)
}

func registerJsFunctions(vm *otto.Otto) (err error) {
	err = vm.Set("btoa", jsBtoa)
	if err != nil {
		return err
	}
	err = vm.Set("atob", jsAtob)
	if err != nil {
		return err
	}
	return
}

```

**Comment by stevenh** [comment]
Indeed not part of the spec.

**Comment by hktalent** [comment]
@niondir 
But I found that the result seems to be different from what is run in js
