### ISSUE TITLE
'DOMParser' is not defined 

### ISSUE THREAD

**Issue by sanxun0325** [robertkrimen/otto#360]
otto nonsupport DOMParser?
why?

![image](https://user-images.githubusercontent.com/28588342/65655434-cc3afe80-e04e-11e9-9957-4bc9f69e365b.png)

**Comment by Asday** [comment]
https://www.ecma-international.org/ecma-262/5.1/

Because it is not in the ECMAScript 5 specification.

**Comment by ghoshabhi** [comment]
@sanxun0325 can you go ahead and close this issue please ?
