### ISSUE TITLE
Wrong byte-indexing of string builtins

### ISSUE THREAD

**Issue by Julio-Guerra** [robertkrimen/otto#371]
Hello,

Quick report of this issue I found and that you can reproduce doing `"'\xe3'".substr(2,1) == "'"`
It basically comes from the fact strings are indexed by byte in the builtins. I quickly fixed it replacing `len()` by the unicode rune count and indexing the string as a `[]rune`. But it would be better to store inside the js string representation the `[]rune` slice instead of the `string`.

I fear this mistake is in a lot of other places. I am probably going to write a lot of new tests to check this.

Let me know what you think. I'd be happy to prepare you the PR.

Details:
- `len()` of the previous string is 4 because utf16 decoding was used. (https://github.com/robertkrimen/otto/blob/master/builtin_string.go#L419)
- Byte-indexing of the string results in the wrong rune index too (https://github.com/robertkrimen/otto/blob/master/builtin_string.go#L438)

**Comment by ghiewa** [comment]
another report [#332](https://github.com/robertkrimen/otto/issues/332)

**Comment by Julio-Guerra** [comment]
@ghiewa https://github.com/dop251/goja doesn't have this critical issue.

**Comment by stevenh** [comment]
This should be fixed now.
