### ISSUE TITLE
Implement way to teardown and close VM

### ISSUE THREAD

**Issue by itsmontoya** [robertkrimen/otto#372]
As a user of Otto. I would love the ability to teardown and close a VM. There are times when I'm running portable code that I want to ensure the code is 100% no longer running and utilizing more resources. I was looking through the godoc and source code, and couldn't find anything that would allow me to call the VM to teardown and close.

**Comment by stevenh** [comment]
If there is no active calls to an `otto` instance aka `vm` it isn't doing anything and if the var goes out of scope it will be cleaned up in due cause. There is no explicit clean up needed.
