### ISSUE TITLE
Support returning []byte from the Value object

### ISSUE THREAD

**Issue by marcsantiago** [robertkrimen/otto#380]
Currently there is only a string method, which required a []byte cast. I'd like to avoid the conversion cost at high volume scale. To avoid the copy and conversion into a string, is can there be a way to return a raw []byte and leave the value.Bytes() and give the user the option to use continue to use value.String(), which would have the added cost.

**Comment by stevenh** [comment]
The internal representation of Value never uses []byte so it would always need a conversion I'm afriad.
