### ISSUE TITLE
Can a single instance of Otto be used safely for highly concurrent work?

### ISSUE THREAD

**Issue by marcsantiago** [robertkrimen/otto#381]
To avoid the cost of creating a vm on a highly concurrent work load, is it possible to create a single instance of *Otto and reuse it safely e.g vm.Run(markupTmp)
and or if its not safe for concurrent use because of some internal state is it possible to add a Reset method allow the user to control the concurrency e.g

mu.Lock()
_, err := vm.Run(markupTmp)
v, _ := vm.Get("foo")
vm.Reset() // <- reset for the next go-rountine to safely use
mu.Unlock()

v.Bytes() (I know bytes doesn't exist yet ;-)... so v.String() )

**Comment by ahmetcanozcan** [comment]
Hi, marc

It's not a real solution for your problem but you can execute your code in a function scope instead of global scope. But this solution fails when your code mutates variables from the global scope. 

I hope it would be helpful
```
mu.Lock()
code := fmt.Sprinf("(function(){ %s; return foo })()",markupTmp)
obj , _ := vm.Object(code)
v := obj.Value()
mu.Unlock()
```

**Comment by Kirides** [comment]
i'd just pool a bunch of VMs and use those, this would reduce locking to a minimum and provide better scalability

**Comment by stevenh** [comment]
This package is not designed for concurrency, so you would need to ensure only one caller is using at time, like with a pool.
