### ISSUE TITLE
有偿解决问题 qq3204235868 急

### ISSUE THREAD

**Issue by black-butler** [robertkrimen/otto#389]
panic: (anonymous): Line 2115:17 Unexpected token ILLEGAL (and 118 more errors)

使用otto框架有此异常抛出 有偿 可以解决的加我qq

**Comment by Asday** [comment]
Please give more information.  We do not have your code and can't reproduce the panic from this.

http://sscce.org/

**Comment by black-butler** [comment]
感谢 已经解决
