### ISSUE TITLE
Saving VM state

### ISSUE THREAD

**Issue by ivoras** [robertkrimen/otto#398]
Is it possible to just save / load the entire VM state, global variables, everything? I'm hoping to use it as a shortcut for running code in a certain context - just save everything to a file (JSON?) and load it later when that particular context is needed.

**Comment by scaba** [comment]
The way I save state with this library is I append every JS code block I execute to a string after successful execution. That string is part of a larger JSON document which I persist to a SQLite DB

When I need to reload the state for that document, I just run that entire stored string through the engine and I have my previous state back
