### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by sahilpaudel-pe** [robertkrimen/otto#403]
I have used `const` in my js script and it isn't compiled by otto.Compile with the message as mentioned in the title.

jsFile
```
const a = 10
const b = 20

function add() {
   return a + b
}
```

sample code actual js is a huge file.

**Comment by Asday** [comment]
`const` is not part of ECMAscript 5.  Look into a transpiler.

**Comment by sahilpaudel-pe** [comment]
Any alternative way to work with it?

**Comment by Asday** [comment]
Write ECMAscript 5 compliant code, or use a transpiler that emits such code.
