### ISSUE TITLE
ReferenceError: 'CryptoJS' is not defined

### ISSUE THREAD

**Issue by KEVISONG** [robertkrimen/otto#412]
Below code have the following output: `ReferenceError: 'CryptoJS' is not defined`

```go
package main

import (
	"github.com/robertkrimen/otto"
)

func main() {
	vm := otto.New()
	_, err := vm.Run(`
		var hash = CryptoJS.SHA256("pass")
		console.log(hash)
	`)
	if err != nil {
		fmt.Println(err)
	}
}
```

Is there a way to import the CryptoJS lib?

**Comment by Asday** [comment]
Bundle it with something like webpack.

**Comment by KEVISONG** [comment]
> Bundle it with something like webpack.

Any specific way to do this?

Is it possible to implement CryptoJS as built-in functions?

**Comment by Asday** [comment]
https://webpack.js.org/guides/getting-started/
