### ISSUE TITLE
Unable to unmarshal js object

### ISSUE THREAD

**Issue by sahilpaudel-pe** [robertkrimen/otto#413]
My js code is returning 
```
return { data: finalResponse, code: 0, message: "success" }
```
and go code is is receiving [object object] note that i don't want to use `JSON.stringify` while returning the response
also the JS script is used in different library so I cannot make this changes.

Any idea how to go about this.

**Comment by Asday** [comment]
`[object object]` is not a thing in go, are you saying that you're receiving a string that reads as that?  How are you "receiving" in the go code?

Consider wrapping your js library in an adapter layer to call from go.  In that adapter layer you can do the stringification.

**Comment by sahilpaudel-pe** [comment]
yes I am receiving`[object object]` as string.

```
	result, err := scriptObject.Call(`evaluate`, nil, ruleSetId, ruleSetVersion.RuleSetVersionData, facts, evaluateVersionId, showTestResults)

```

the result  is `[object object]`

**Comment by chrislowth** [comment]
what does

result.IsString()

return?

**Comment by sahilpaudel-pe** [comment]
This is giving me `false`

**Comment by chrislowth** [comment]
So - you're not getting a string back after all (objects are displayed as
"[object object]" when they are printed)..

The returned object can be accessed using result.Object() - you then have
access to it's fields and methods from there.

**Comment by sahilpaudel-pe** [comment]
Yes I am getting the data using `.Get("key")` but how can I unmarshall this data to a struct model

json data returned by jscode

```
{ data: {"result":{"name": "sahil", "age":10}}, code: 0, message: "success" }
```

the object inside result is always varying.

Can you please suggest how can I unmarshall it to struct

**Comment by stevenh** [comment]
If you don't know the type then you would need to unmarshal into `map[string]interface{}` if you do you would need to pass the string into golang method e.g.
```go
vm.Set("unmarshal", func(call otto.FunctionCall) otto.Value {
    // TODO: unmarshal call.Argument(0).String() here and return.
    return otto.Value{}
})
