### ISSUE TITLE
Parse JavaScript string, not file

### ISSUE THREAD

**Issue by 89z** [robertkrimen/otto#414]
I would like to parse some JavaScript, so I went to this page [1], and found these methods:

~~~
func NewParser(filename, src string) Parser
func ParseFile(fileSet *file.FileSet, filename string, src interface{}, mode Mode) (*ast.Program, error)
func ParseFileWithSourceMap(fileSet *file.FileSet, filename string, javascriptSource, sourcemapSource interface{}, mode Mode) (*ast.Program, error)
func ParseFunction(parameterList, body string) (*ast.FunctionLiteral, error)
func ReadSource(filename string, src interface{}) ([]byte, error)
func ReadSourceMap(filename string, src interface{}) (*sourcemap.Consumer, error)
func TransformRegExp(pattern string) (string, error)
~~~

but none of them seem to be quite right. I dont have a file, I just have some JavaScript code in a string, such as:

~~~js
var x = 'lorem ipsum';
~~~

Is a function available for that use case?

1. https://godocs.io/github.com/robertkrimen/otto/parser

**Comment by Asday** [comment]
https://godocs.io/github.com/robertkrimen/otto#hdr-Parser

```
filename := "" // A filename is optional
src := `
    // Sample xyzzy example
    (function(){
        if (3.14159 > 0) {
            console.log("Hello, World.");
            return;
        }

        var xyzzy = NaN;
        console.log("Nothing happens.");
        return xyzzy;
    })();
`

// Parse some JavaScript, yielding a *ast.Program and/or an ErrorList
program, err := parser.ParseFile(nil, filename, src, 0)
```

Does that not solve your issue?

**Comment by 89z** [comment]
@Asday ah, sorry about that. It does seem to be somewhat documented in some places, but these functions are missing the documentation:

~~~
func NewParser(filename, src string) Parser
func ParseFileWithSourceMap(fileSet *file.FileSet, filename string, javascriptSource, sourcemapSource interface{}, mode Mode) (*ast.Program, error)
func ReadSource(filename string, src interface{}) ([]byte, error)
func ReadSourceMap(filename string, src interface{}) (*sourcemap.Consumer, error)
~~~

**Comment by Asday** [comment]
I'm struck by a couple thoughts: the docs I found are right in the main package documentation so they're not super hard to find; the function mentioned in the snippet I copy pasted is not one of the ones you note as missing documentation; and if the ones in which you're interested are missing documentation, perhaps this is a fantastic opportunity for you to make a PR for them!  Documentation PRs are some of the best in the world, after all.

**Comment by 89z** [comment]
@Asday no thanks. I would like to do it, but I am very busy with some other projects. Maybe another time.

**Comment by 89z** [comment]
I think I will close this, as the other function looks to actually be a lexer rather than a parser, so for my use case, your example is good. Thanks again
