### ISSUE TITLE
Invalid Idx0

### ISSUE THREAD

**Issue by 89z** [robertkrimen/otto#415]
Using this code:

~~~go
package main

import (
   "fmt"
   "github.com/robertkrimen/otto/ast"
   "github.com/robertkrimen/otto/parser"
)

type visit struct{}

func (visit) Exit(ast.Node) {}

func (v visit) Enter(n ast.Node) ast.Visitor {
   fmt.Printf("%v %#v\n", n.Idx0(), n)
   return v
}

func main() {
   pro, err := parser.ParseFile(nil, "", "var x = [10,11];", 0)
   if err != nil {
      panic(err)
   }
   var vis visit
   ast.Walk(vis, pro)
}
~~~

I get this result:

~~~
1 &ast.Program{Body:[]ast.Statement{(*ast.VariableStatement)(0xc00004c500)}, DeclarationList:[]ast.Declaration{(*ast.VariableDeclaration)(0xc00004c4e0)}, File:(*file.File)(0xc000076660), Comments:ast.CommentMap{}}
1 &ast.VariableStatement{Var:1, List:[]ast.Expression{(*ast.VariableExpression)(0xc0000766c0)}}
5 &ast.VariableExpression{Name:"x", Idx:5, Initializer:(*ast.ArrayLiteral)(0xc000076750)}
9 &ast.ArrayLiteral{LeftBracket:9, RightBracket:15, Value:[]ast.Expression{(*ast.NumberLiteral)(0xc0000766f0), (*ast.NumberLiteral)(0xc000076720)}}
10 &ast.NumberLiteral{Idx:10, Literal:"10", Value:10}
13 &ast.NumberLiteral{Idx:13, Literal:"11", Value:11}
~~~

The problem is, the index for the ArrayLiteral `9` is not valid. It should be `8`.

**Comment by stevenh** [comment]
It looks correct here as idx starts at one and not zero
```js
var x = [10,11];
133456789
```

**Comment by 89z** [comment]
I believe Go strings index starts at zero. Do you know the justification why a different indexing system was chosen? Also, is it documented anywhere? I checked this entire page, but didnt see it:

https://godocs.io/github.com/robertkrimen/otto/ast

**Comment by stevenh** [comment]
You're right I don't think its called out you can actually find it in the [code which influences this here](https://github.com/robertkrimen/otto/blob/master/parser/parser.go#L106).

As to the reason I'm afraid that pre-dates me.

**Comment by 89z** [comment]
Looks like it was first added in 2014:

https://github.com/robertkrimen/otto/commit/ad8a97c028da9cb19d91de09a1c8315c734d9f99

Although I am not seeing a reason for the choice. If I had to guess, maybe its so that `0` could be used as a sentinel value? But I would think `-1` would be fine for that, as thats what the standard library already uses for stuff like `strings.Index`.

**Comment by stevenh** [comment]
Yep, OK to close @89z ?

**Comment by 89z** [comment]
No. I would like Idx0 to be zero index. So if I a a PR, can it be accepted?

**Comment by stevenh** [comment]
Unfortunately that’s a breaking change so we can’t change that behaviour now sorry

**Comment by 89z** [comment]
how is it a breaking change? From what I can tell, its not even documented as I linked earlier.

**Comment by stevenh** [comment]
Any user of the package who uses those values could have their code broken by changing it from 1 indexed to 0 indexed.

So even though it’s not documented it’s not something we can change I’m afraid

**Comment by 89z** [comment]
OK, I understand
