### ISSUE TITLE
Is there any way to add builtin functions?

### ISSUE THREAD

**Issue by marcecaro** [robertkrimen/otto#425]
Is there any way to add builtin functions?
I need  a way to inject my own functions hosted in golang and call them from javascript. This is useful to inject 'kind of sdk' so the people that use the sdk (plugins developers in my case) can use High level functions provided by the platform.

**Comment by Ashtonian** [comment]
see readme 
```golang
vm.Set("sayHello", func(call otto.FunctionCall) otto.Value {
    fmt.Printf("Hello, %s.\n", call.Argument(0).String())
    return otto.Value{}
})```
