### ISSUE TITLE
feature request: support template literals

### ISSUE THREAD

**Issue by flyn-org** [robertkrimen/otto#426]
The otto package does not seem to support template literals, which are documented at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals. Here is a minimum example:
```go
package main

import (
	"fmt"
	"github.com/robertkrimen/otto"
	"os"
)

func main() {
	vm := otto.New()
	js := "document.location=`http://localhost/...`"
	if _, err := vm.Run(js); err != nil {
		fmt.Fprintf(os.Stderr, "error simulating %s: %s\n", js, err.Error())
	}
}
```
This prints `error simulating document.location=`http://localhost/...`: (anonymous): Line 1:19 Unexpected token ILLEGAL (and 1 more errors)`, seemingly objecting to the grave accent.

**Comment by Asday** [comment]
https://github.com/robertkrimen/otto/blob/master/README.markdown#caveat-emptor

> Otto targets ES5. ES6 features (eg: Typed Arrays) are not supported.
