### ISSUE TITLE
Question: How to run `export default { entry: './src/index.ts' } `

### ISSUE THREAD

**Issue by renzp94** [robertkrimen/otto#438]
I have a file `config.ts`, the content is `export default { entry: './src/index.ts' }`.
I want get  struct `{entry: './src/index.ts'}`.
I try `vm.Run`, error: `(anonymous): Line 1:1 Unexpected reserved word`
What shall I do?
I hope you can answer my questions. Thank you very much

**Comment by Asday** [comment]
> Otto targets ES5. ES6 features (eg: Typed Arrays) are not supported.

https://github.com/robertkrimen/otto#caveat-emptor

Typescript is not javascript.

**Comment by renzp94** [comment]
ok.Thanks.
