### ISSUE TITLE
parser.ParseFile difference between []byte and file

### ISSUE THREAD

**Issue by ttttmr** [robertkrimen/otto#439]
```go
body := []byte("xxx...")
var err error
ioutil.WriteFile("test.js", body, 0644)

_, err = parser.ParseFile(nil, "", body, 0)
log.Info(err) // (anonymous): Line 4:3 Unexpected reserved word (and 24 more errors)
_, err = parser.ParseFile(nil, "test.js", "", 0)
log.Info(err) // <nil>
```

body is correct js code, but their parsing results are different
[js file](https://blog.xlab.app/js/config.js)

**Comment by ttttmr** [comment]
I want to parse the body but not create the file, how to do it

**Comment by stevenh** [comment]
You can do this with [parser.ReadSource](https://pkg.go.dev/github.com/robertkrimen/otto@v0.0.0-20221025135307-511d75fba9f8/parser#ReadSource)
