### ISSUE TITLE
JS VM crashing go 

### ISSUE THREAD

**Issue by ssharish** [robertkrimen/otto#444]
This is not a bug, more of an ask, since I could not find any relevant information anywhere.  

Is it possible to run JS VM as a separate process detached from the GO binary in which it is used? or 
Is there a way to not crash GO binary during runtime, due to JS code error, e.g. JS stackoverflow?

Thanks in advance.

**Comment by stevenh** [comment]
As it's running go code you couldn't run it separately, however you could have your app run the vm in a separate process, but hat more a task of your app than this library.

That said do you have a small test which replicates this?

**Comment by ssharish** [comment]
Thanks Steven.
