### ISSUE TITLE
new Date can't not parse datetime string

### ISSUE THREAD

**Issue by lyr-2000** [robertkrimen/otto#489]
new Date can't not parse time string  format 

```js
var t = '2023/02/23 11:23:57'
console.log( new Date (t)) // it 's wrong , get     Invalid Date
console.log( new Date( 1677122637000)  )
console.log( new Date( 1677122637000).toLocaleString()  )


```

//output:
```
Invalid Date
Thu, 23 Feb 2023 11:23:57 CST
2023-02-23 11:23:57

```

expect  output is 
```
Thu Feb 23 2023 11:23:57 GMT+0800
Thu Feb 23 2023 11:23:57 GMT+0800
2023-02-23 11:23:57
```

**Comment by stevenh** [comment]
While browsers may support this it isn't a mandated part of the spec:
> Only the [ISO 8601 format](https://tc39.es/ecma262/#sec-date-time-string-format) (YYYY-MM-DDTHH:mm:ss.sssZ) is explicitly specified to be supported. Other formats are implementation-defined and may not work across all browsers. A library can help if many different formats are to be accommodated.

You can see the formats that otto currently supports [here](https://github.com/robertkrimen/otto/blob/master/type_date.go#L225)

That said it's easy to add please try https://github.com/robertkrimen/otto/pull/490 to confirm it works for you.

**Comment by stevenh** [comment]
@lyr-2000 did you manage to test #490 ?
