### ISSUE TITLE
Javascript not working

### ISSUE THREAD

**Issue by romanoff** [robertkrimen/otto#49]
I tried to use otto to render soy template, but it didn't seem to work. Here is javascript example:
http://pastebin.com/wvvGABEr

When I use node.js, seems to work just fine.

**Comment by xyproto** [comment]
Does it work if you use [this fork of otto](https://github.com/xyproto/otto) instead? (same changes as in pull request #205). It's supposed to be compatible with how regex is handled in JavaScript, but needs more testing.

**Comment by stevenh** [comment]
Example not available any more, so closing.
