### ISSUE TITLE
does it use v8 under the hood? anything cgo?

### ISSUE THREAD

**Issue by sprappcom** [robertkrimen/otto#523]
1. saw this: https://github.com/robertkrimen/otto/issues/54 
would like to allow others to run js on my server too. how much of a "vm" "isolate" is v8 being used or something? if the js code crash, will it take down the golang program too?

2. how does this compare with github.com/rogchap/v8go?

trying to figure out what's the best way forward to allow others to run js on my server that's all.

**Comment by stevenh** [comment]
This is for issues not questions, please use something like [stackoverflow](https://stackoverflow.com/) for questions.

That said:
1. No this is native go, if the JS is broken it shouldn't take down the program, but to ensure this is case you can always use a [panic recovery.](https://go.dev/blog/defer-panic-and-recover)
2. I can't comment as I've not use v8go
