### ISSUE TITLE
Regular expression error: Invalid regular expression: re2: Invalid \1 <backreference> (and 1 more errors)

### ISSUE THREAD

**Issue by tocha688** [robertkrimen/otto#530]
Invalid regular expression: re2: Invalid \1 <backreference> (and 1 more errors)

```
var fullRegex = /^-----BEGIN ((?:.*? KEY)|CERTIFICATE)-----([0-9A-z\n\r+/=]+)-----END \1-----$/m;
```

**Comment by stevenh** [comment]
This is a known limitation as the current implementation uses re2 syntax. If you're interested in having this work please test out https://github.com/robertkrimen/otto/pull/480 which provides configurable regexp including fully javascript compatibility.
