### ISSUE TITLE
A string issue when dealing with Chinese.

### ISSUE THREAD

**Issue by dingdinglz** [robertkrimen/otto#534]
When I run this code,I can't get the wanted response.

```go
package main

import (
	"github.com/robertkrimen/otto"
)

func main() {
	vm := otto.New()
	vm.Run(`
	var Message = "发送 213123";
    index = (Message).indexOf(' ') + 1;
	console.log(Message.slice(0,index-1));
	`)
}
```

I think the correct res is 

![ISSUE2](https://github.com/user-attachments/assets/db478a12-7dff-4d5b-b62d-0a1836be4e7a)

But I get this

![ISSUE3](https://github.com/user-attachments/assets/39c8b1fe-b737-41ac-9cb9-c959a5f51d6d)

Maybe there are some errors in otto?

I can't sure,so I send this issue.Maybe you can help me.I think it may link to Chinese.

When I replace the "发送" with "send" , I can get the right answer.

Thank you for your help.

**Comment by stevenh** [comment]
Thanks for the report @dingdinglz could you try #535 to confirm it fixes your use case please.

**Comment by dingdinglz** [comment]
Thank you for your help.The problem has been corrected.
