### ISSUE TITLE
Resource control

### ISSUE THREAD

**Issue by zond** [robertkrimen/otto#54]
I am interested in letting end users create and run js on my server. To make this safe, I would like to control the amount of memory and cpu they can use.

Would this be feasible in otto? Would it be hard to implement? Where should I begin?

**Comment by scorredoira** [comment]
Hi, did you get any further limiting memory usage with unsafe.SizeOf and runtime.SetFinalizer?

**Comment by zond** [comment]
Sorry, I didn't. Limiting the execution speed had a central point of attack, but allocations were made all over the place.

I postponed it indefinitely when I realized :/

**Comment by scorredoira** [comment]
OK, I will try cgroups in a different process then. Thank you!

**Comment by zond** [comment]
Good luck :)

**Comment by stevenh** [comment]
This is really outside of the purview of this package.
