### ISSUE TITLE
Using the `.Set` function to embed a struct with lower case method names

### ISSUE THREAD

**Issue by tombousso** [robertkrimen/otto#65]
Is it possible to use the `.Set` function to embed a struct into the JS, like you can do with functions of type `otto.FunctionCall`? I looked at the source and for embedding the `console` "class" into the JS the `_runtime` and `_object` types are used, however they don't seem to be exposed so is this possible?

The `newConsoleObject` function I'm referring to can be found at https://github.com/robertkrimen/otto/blob/ad8a97c028da9cb19d91de09a1c8315c734d9f99/inline.go#L6037

**Comment by erwinvaneyk** [comment]
Hey @robertkrimen - this issue is still relevant, right? If so, regarding this issue, what about using field tags for this?:
```golang
type Foo struct {
  Bar int `otto:"bar"`
}
// ...
otto.Set("foo", Foo{ Bar : 42 })
// Would allow
otto.Eval("foo.bar")
```
Or, you could reuse the JSON field tags for it. Would this be a suitable solution in your opinion?

**Comment by stevenh** [comment]
That's a really interesting idea.
