### ISSUE TITLE
Add additional information to runtime errors

### ISSUE THREAD

**Issue by nd2s** [robertkrimen/otto#66]
Would it be possible to add some additional information to runtime errors?
Errors like that are pretty hard to track down:

```
TypeError: Cannot access member 'type' of undefined
ReferenceError: bla is not defined
```

Ideally that would be a line number, but I assume that's hard to impossible to implement.

**Comment by saturn4er** [comment]
How can I cast error to otto.Error and get this information? This doesn't work

    oerr, e := err.(otto.Error);
