### ISSUE TITLE
Memleak caused by Otto clones?

### ISSUE THREAD

**Issue by nd2s** [robertkrimen/otto#71]
I'm holding a few otto runtimes in memory and use .Clone() to get quick copies before adding some context specific stuff to them.

It is then executed and Otto objects get just out of scope. There is no permanent storage of these clones.

It seems this memory is never freed. mem profiling:

```
github.com/robertkrimen/otto.objectClone - 20% of total heap
github.com/robertkrimen/otto.(*declarativeEnvironment).clone - 62%
```

**Comment by matiasinsaurralde** [comment]
Hi, I'm experimenting something like this, memory keeps growing on each request, any ideas?

**Comment by deoxxa** [comment]
Code?

**Comment by mvdan** [comment]
@deoxxa apologies for not replying last year. I've been looking into it and haven't been able to reproduce any issue like the one Matias described above.

If we do find one and it turns out to be a bug in Otto, I'll be sure to report it. For now, there is no reason to think there is one.

**Comment by stevenh** [comment]
Unable to reproduce
