### ISSUE TITLE
negative stack trace line numbers being reported by Otto.

### ISSUE THREAD

**Issue by c4milo** [robertkrimen/otto#91]
I'm compiling and running a script that throws a TypeError and I'm seeing wrong line numbers being reported by Otto:

```shell
TypeError
    at merge (Helixfile:1:-1)
    at config (Helixfile:-4598:-2916)
    at Helixfile:42:1

!      Error loading Helixfile. This is a bug, please let us know about it.
```

**Comment by dop251** [comment]
This may be fixed by https://github.com/robertkrimen/otto/pull/115

**Comment by stevenh** [comment]
@c4milo can you confirm you still have an issue please?

**Comment by c4milo** [comment]
Unfortunately no :( I moved to other projects long time ago and lost track of this specific one.

**Comment by stevenh** [comment]
Thanks for confirming @c4milo I'll close this for now, if you need to you can reopen.
