### ISSUE TITLE
How to remove some function of js?

### ISSUE THREAD

**Issue by dingoxiong** [robertkrimen/otto#98]
I like this project . I want to use it as an script engine in golang service.
But i need remove some function of js, for security reason.
For example: do not allow the script to read or write file directly.
also, the parser.go.
Any optional settings?  if need to change the code , please give some example.
Thanks !

**Comment by robertkrimen** [comment]
By default, otto does not expose any interface for file reading/writing or going out to a network.

It only implements the functionality in the ECMA document.

The file-reading portion of the parser is not accessible within the environment.
