### ISSUE TITLE
repl?

### ISSUE THREAD

**Issue by glycerine** [robertkrimen/otto#99]
Hi Robert,

is it possible to use otto as a javascript repl (interactive command line prompt)?  If so, could you suggest how would I do that?

Thank you.

Jason

**Comment by emicklei** [comment]
a simple example http://ernestmicklei.com/2014/02/12/javascript-cli-in-go-using-otto/

if you need real cli behavior, i suggest you have a look at https://github.com/GeertJohan/go.linenoise

**Comment by stevenh** [comment]
@glycerine does @emicklei answer fully address your question? If so please close this issue, if not please expand on  your requirements.

**Comment by glycerine** [comment]
@stevenh thanks for checking; yes and closing out.
